### ISSUE TITLE
kayit sonrasi e-posta gonderimi

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#1]
kayit olan kisiye onay e-posta gonderilmesi

**Comment by ackepenek** [comment]
Tamamlanan ve eksik kalan kısım:
- [x] Sisteme hem admin panel'den kullanıcı eklendiğinde hem uygulamadan kaydolundugunda email dogrulama linki gönderilmesi
- [x] Dogrulama linkine tıklandıgında hesabın aktif edilmesi
- [ ] Dogrulama linkinin geçerlilik süresinin kontrolu
