### ISSUE TITLE
Tercihler dondurulduktan sonra katımcının başvurusunu iptal etmesi durumunda kullanıcının journal'una not düşülmesi

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#100]
Tercihler dondurulduktan sonra katımcının başvurusunu iptal etmesi durumunda bu konuda profiline "tercihler dondurultundan ama kabulu yapılmadan önce iptal etti" diye not düşülür ve bu uyarının varlığı kullanıcıya bildirililir. İptal ederken de bunun yapılacağı şeklinde kendisine yemin ettirilir.

**Comment by ozgebarbaros** [comment]
başvuru süresi bitiminde kullanıcı hiç bir kursa kabul almadan tüm başvurularını iptal ederse journal'ına "Kursların başlamasına x gun kala tüm başvurularını iptal etti." diye not düşülür. Eğer bir iptal sebebi girmişse not şu şekilde olur: "Kursların başlamasına x gun kala tüm başvurularını iptal etti. İptal sebebi: ...."
başvuru süresi bitiminden sonra kabul almış olmasına rağmen tüm başvurularını iptal ederse ve bir iptal sebebi belirtirse not şu şekilde olur: "Kursların başlamasına x gun kala tüm başvurularını iptal etti. Tercihi kursun başlamasına y gün kala kabul edilmiş. İptal sebebi: ...."

Başvuru süresi içerisinde tüm başvurularımı iptal ederken bir neden belirtirse kullanıcının journal'ına not düşer. Aksi halde bir not düşülmez.
