### ISSUE TITLE
Journal girildiğinde sistem journal'ına not düşülmesi

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#102]
Journal girdilerinde "kim girdi?", "ne zaman girdi?", sistemin kendi girdiği jurnallerde sistemin bunun girdiğine dair bilginin bulunması.

**Comment by ozgebarbaros** [comment]
#84 ile ilişkili

**Comment by ozgebarbaros** [comment]
Kişi ile ilgili girilen journallarda kimin ne zaman girdiği bilgisi tutuluyor.
