### ISSUE TITLE
Kullanıcının tercihinin yönetici ya da eğitmenler tarafından değiştirilimesi durumunda bunun journal'a not düşülmesi

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#103]
Kullanıcının tercihinin yönetici ya da eğitmenler tarafından değiştirilimesi durumunda bunun journal'a not düşülmesi

**Comment by ozgebarbaros** [comment]
#84 ile ilişkili

**Comment by ozgebarbaros** [comment]
egitmen tarafından eklenen notlar 'kurs', sistem tarafından eklene notlar 'sistem' yoneticinin ve egitmenin tercihler üzerinde yaptigi işlemler sonrasi eklenen notlar 'tercih' diye etiketleniyor.
Bu notlar eğitmenlere ve admine görünür durumda.
