### ISSUE TITLE
Bir kullanıcının tüm tercih değişikliklerinin kim ve ne zaman yapıldığı ile birlikte loglanması istenirse ayrı bir tab da kullanıcı profilinde görüntülenmesi

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#104]
Bir kullanıcının tüm tercih değişikliklerinin kim ve ne zaman yapıldığı ile birlikte loglanması istenirse ayrı bir tab da kullanıcı profilinde görüntülenmesi

**Comment by ozgebarbaros** [comment]
#103 ile ilişkili

**Comment by ozgebarbaros** [comment]
Ayrı bir tab'da görüntüleme işlemi şimdilik sadece admin için mümkün.
Yönetim panelinden Katılımcı notları bölümünden filtre bölümünden 'kurs', 'sistem' ve tercihten birinin seçilmesi durumunda seçilen filtredeki etikete sahip notlar listelenir.

**Comment by ozgebarbaros** [comment]
yeni bir tab'da görüntüleme isteği gelmesi durumunda yeni iş açılır.
