### ISSUE TITLE
Eğitmenlerin sadece kendi kurslarına başvurmuş kişilerin journal entry'lerini görebilmesi

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#106]
Eğitmenlerin sadece kendi kurslarına başvurmuş kişilerin jurnal entry'lerini görebilmesi

**Comment by ozgebarbaros** [comment]
Eğitmenler sadece kendi kurslarına başvuran kişilerin journal entry'lerini görebiliyorlar.
