### ISSUE TITLE
Eğitmenin kendi verdiği eğitime katılan kursiyerler dışında kalan kursiyerlerin, sadece o eğitmenin kendi girdiği entry leri görebilmesi.

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#107]
Eğitmenin kendi verdiği eğitime katılan kursiyerler dışında kalan kursiyerlerin, sadece o eğitmenin kendi girdiği entry leri görebilmesi.

**Comment by ozgebarbaros** [comment]
#84 ile ilişkili

**Comment by ozgebarbaros** [comment]
#108 ile aynı.
