### ISSUE TITLE
Eğitmenlerin sadce kendi eğitimlerine başvurmuş olan kişilerin journal entry'lerini görebilmesi. Diğerlerinin kendi profillerinde ise sadece eğitmenin kendi yazdığı jurnal entry lerini görebilmesi değiştirebilmesi ve silebilmesi

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#108]
Eğitmenlerin sadce kendi eğitimlerine başvurmuş olan kişilerin journal entry'lerini görebilmesi. Diğerlerinin kendi profillerinde ise sadece eğitmenin kendi yazdığı jurnal entry lerini görebilmesi değiştirebilmesi ve silebilmesi.

**Comment by ozgebarbaros** [comment]
#84 ile ilişkili

**Comment by ozgebarbaros** [comment]
Eğitmenler sadece kendi kurslarına başvurmuş kişilerin profillerini görüntüleyebiliyorlar. Bir katılımcının profilini o katılımcının başvurduğu kurslar ile ilgisi olmayan eğitmenlerin görebileceği bir ortam sağlamıyoruz. Yani bir kişinin profilini sadece başvurduğu kursun eğitmeni ve yoklamayı sisteme girecek operator ve admin görebilir. 

Eğitmenlerin kendi sayfasında bir ekran oluşturarak. Daha önce katılımcılar hakkında sisteme girdiği (geçmiş etkinlikler de dahil olmak üzere) yorumları görüntüleyip silebilmesi gerekir

**Comment by dfisek** [comment]
Operatörün profili görmesi gerekmiyor. Mevcut etkinlik içn yoklama girebilmesi ve düzeltebilmesi yeterli.

Bir de etkinlik kapatıldıktan sonra, eğitmenin artık o kişilerin profiline (tekrar kendi eğitmeni olduğu bir etkinliğe başvurana kadar) görememesi gerekir.

**Comment by ozgebarbaros** [comment]
"Bir de etkinlik kapatıldıktan sonra, eğitmenin artık o kişilerin profiline (tekrar kendi eğitmeni olduğu bir etkinliğe başvurana kadar) görememesi gerekir." bu durumda bunu sağladığımız için bu işi kapatıyorum.
