### ISSUE TITLE
Eğitmenler kabul epostaları gönderildikten sonra da yeni kişiler seçmeye devam edebililriler

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#110]
Eğitmenler kabul epostaları gönderildikten sonra da yeni kişiler seçmeye devam edebililriler, kabul süreci tamamlandıktan sonra kamp başlayana kadar yeni kişileri kurslarına kabul
etmeye devam edebilmemiler. bu süreçte kişinin 1. 2. 3. tercihi olmasına bakmaksızın, seçim esnasında kabul epostası gönderebilirler ve daha sonra bu seçim değiştirilemez. bu şekilde
ek yerleştirmeyele yerleşen kişilerin "ek yerleşmeyle yerleştirildi" bilgisinin saklanması gerekir. kamptan önce iptal etmeleri durumunda kişinin jurnanilke kampa x gün kala ek
yerleştirme ile yerleştirildi ve y gün kala bunu iptal etti şeklinde not düşülmesi gerekir.

**Comment by ozgebarbaros** [comment]
#83 ile ilişkili

**Comment by ozgebarbaros** [comment]
Tercih dönemi bitiminden kurs başlangıcına kadar egitmen kendi kursuna el ile kursiyer ekleyebilir. Eğitmenlerin ekledigi tercihler journal'a kaydediliyor.
