### ISSUE TITLE
Etkinliğe kabul edilen kaç erkek, kaç kadın katılımcı olacağının listesi alınabilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#112]
Etkinliğe kabul edilen kaç erkek, kaç kadın katılımcı olacağının listesi alınabilmeli. Her bir kurs için ayrı ayrı alınabilmeli aynı zamanda bunlardan sadece yurrtta konaklayanlar veya kendisi
zaten kyk yurtlarında kalıyorlar şeklinde bilgileri çekilebilmeli.

**Comment by ozgebarbaros** [comment]
Alınacak csv çıktısında kabul edilen katılımcıların ad,soyad,email,kurs,cinsiyet ve konaklama tercih bilgileri yer alıyor. Çıkan csv üzerinden kurs bazında filtreleme yapılabilir.
Konaklama tercihleri sisteme eklenirken tercihlerden biri "KYK Kız/Erkek yurdu (halihazırda kyk yurtlarında kalıyor)" olur ve yine bu seçeneği işaretlemiş olanlar alınan csv çıktısından filtrelenebilir.

**Comment by dfisek** [comment]
Bence şu aşamada yeterli bu. Zaten etkinlik başına bir-iki kere alınacak bir liste, onda da CSV'den filtreleme yapılabilir.

Geleceğe dönük düşük öncelikli bir iyileştirme olarak bunun web arayüzünden doğrudan yapılabilmesi olarak kalabilir. Canı isteyen yapar şeklinde.

**Comment by ozgebarbaros** [comment]
Ben eksik söylemişim. Filtrelemeyi İşelmler > Tüm Kullanıcılar sayfası üzerinden Bul kutucuğuna (kurs adına veya konaklama tercihine göre) yazılıp filtreleme yapıldıktan sonra sadece o arama ve sıralama sonucunun csv olarak çıktısını alabilirsiniz.
