### ISSUE TITLE
Kamp başladıktan sonra katılımcı başvurusunu iptal edememeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#113]

**Comment by ozgebarbaros** [comment]
Site modeline kurs/kamp başlama tarihi eklenmesi gerekiyor. Tüm başvuruları iptal et özelliğinin de bu tarihe göre kontrol edilmesi gerekiyor.

**Comment by dfisek** [comment]
Kamp başlangıç/bitiş tarihinin elde olması yeterli. Kursların farklı başlangıç/bitiş tarihleri yok.

**Comment by ozgebarbaros** [comment]
@dfisek Kurs derken akademik bilişimi de düşündüm. yani evet başlangıç ve bitiş tarihi tüm kurslar için aynı olacak.

**Comment by dfisek** [comment]
Akademik Bilişim için de aynısı geçerli aslında, onda da tüm kurslar aynı tarihte başlayıp aynı tarihte bitiyor. "Etkinlik" için başlangıç/bitiş tarihi yeterli olmalı tutmak için.

**Comment by ozgebarbaros** [comment]
Evet bunun için etkinlikten etkinliğe değişen tüm site üzerinde  uygulanan ortak bilgileri tuttuğumuz Site modelimiz var  (etkinlik/kamp/kurs ne derseniz:)) başlangıç ve bitiş tarihi de buraya eklenecek.

**Comment by ozgebarbaros** [comment]
Kamp başladıktan sonra katılımcı başvurusunu iptal edemez.
