### ISSUE TITLE
Her bir kursun yoklama kayıtlarınını da sisteme girilebilmesi gerekir

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#114]
Her bir kursun yoklama kayıtlarınını da sisteme girilebilmesi gerekir. Yoklamalar her kurs günü sabah, öğle ve akşam şeklinde işlenir. İlgili zaman aralığı için 4 farklı state olmalıdır.
-katıldı
-katılmadı 
-yarısına katıld9
-kurs yapılmadı.

**Comment by ozgebarbaros** [comment]
yönetici ve/veya bu iş için yetkilendirilmiş bir kullanıcının yoklama verilerini girebilmesi için ekran hazırlandı. İşlemler > Yoklama adımında. (Yoklamanın aktif olabilmesi için site modeline kurs/kamp/etkinlik başlangıç bitiş tarihlerinin eklenmesi gerekiyor.)
