### ISSUE TITLE
Bir katılımcının kursun kaç saatine katıldığı ve kursun toplam saat miktarını, tüm katılımcılar için bir liste şeklinde çıkartılması

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#115]
Bir katılımcının kursun kaç saatine katıldığı ve kursun toplam saat miktarını, tüm katılımcılar için bir liste şeklinde çıkartılması gerekmektedir. Katılım yüzdesi de bu raporda yer almalıdır.

**Comment by ozgebarbaros** [comment]
#118 ile ilişkili. #118 yapıldıktan sonra bu tür bir bilgi istatistik sayfasına konulabilir. Sadece admin erişimine açık olur.

**Comment by ozgebarbaros** [comment]
#114 ile ilişkili. #114 yapıldıktan sonra bu tür bir bilgi istatistik sayfasına konulabilir. Sadece admin erişimine açık olur.

**Comment by dfisek** [comment]
İstatistik sayfası olarak bir yerde toplayacaksak bu bilgileri, istatistik sayfasına erişebilen ek bir kullanıcı yetkisi iyi olabilir. Bu bilgilere sadece adminin erişmesi gerekmiyor.

**Comment by ozgebarbaros** [comment]
@dfisek bu durumda daha fazla rol tanımlamamız ve hangi özelliklere hangi rollerin erişeceğini belirlememiz gerekiyor.
Şimdilik sistemde üç tip kullanıcı var eğitmen, kursiyer ve admin. İşleri gruplayarak başlayabiliriz. İşleri grupladıktan sonra roller de ortaya çıkar diye düşünüyorum.

**Comment by ozgebarbaros** [comment]
bu iş yapıldı.
