### ISSUE TITLE
Kurslara hangi eğitmenlerin girdiği bilgisinin tutulması konusunda bir çalışma yapılabilir

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#116]

**Comment by ozgebarbaros** [comment]
Kurslara hangi eğitmenlerin girdiği bilgisi tutuluyor. Kurslarda şube oluşturma ve hangi şubeye hangi eğitmenin girdiği bilgisi #117 nolu işte yapılacak.
