### ISSUE TITLE
Yoklama listelerinin doğrudan uygulama taarafından pdf olarak üretilmesi konusunda çalışma yapılabilir

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#118]

**Comment by ozgebarbaros** [comment]
#114 ile ilişkili.

**Comment by ozgebarbaros** [comment]
Görevli kullanıcı ile giriş yaptıktan sonra islemler menüsünden > tüm kabul edilenler adımından yoklama durumunun exportu alınabilir.
