### ISSUE TITLE
Kullanıcının başvurusuna görevlendirme yazısı veya veli izin yazısını ekleyebilmesi gerekir

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#119]
Kullanıcının başvurusuna görevlendirme yazısı veya veli izin yazısını ekleyebilmesi gerekir. Kişinin başvurusuna gerekirse ekj evrak (örnç gövrevlendirme yazısı) ekleyebilmeli.

**Comment by ozgebarbaros** [comment]
userprofile adımından belge eklenebilir.
