### ISSUE TITLE
Kursa Katılımcıların Kabul Edilmesi Prosedürü

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#121]
Eğitmen kursuna kişi seçerken: kursu eğer kişinin 3. tercihi ise ve bu kişi 1. veya 2. tercihi olan kurs tarafından seçildiyse, eğitmen o kişi seçememeli ama kişinin hangi kursu seçtiğini ve bu kursun kaçıncı tercihi olduğunu görebilmeli.

Eğitmen kursuna kişi seçerken: kişi başka tercih ettiği bir kursa seçildiyse bunu görebilmeli (hangi kurs ve kaçıncı tercihi olduğunu). kurs eğer kişinin 2. tercihi ise ve bu kişi 1. tercihi olan kurs tarafından seçildiyse, eğitmen o kişiyi seçememeli. Eğer katılımcı 3. tercihi olan kurs tarafından seçildiyse eğitmen onu kursuna seçebilmeli. Seçtiğinde ise kişi 3. tercihi olan eğitmene kişinin 2. tercihine kaydırıldığına dair eposta gönderilmeli.

Eğitmen kursuna kişi seçerken:  kişi başka tercih ettiği bir kursa seçildiyse bunu görebilmeli (hangi kurs ve kaçıncı tercihi olduğunu). eğer katılımcı 2. ya da 3. tercihi olan kurs tarafından seçildiyse eğitmen onu kursuna seçebilmeli. Seçtiğinde ise kişiyi seçmiş olan eğitmene kişinin 1. tercihine kaydırıldığına dair eposta gönderilmeli.

**Comment by ozgebarbaros** [comment]
"Eğitmen kursuna kişi seçerken: kursu eğer kişinin 3. tercihi ise ve bu kişi 1. veya 2. tercihi olan kurs tarafından seçildiyse, eğitmen o kişi seçememeli ama kişinin hangi kursu seçtiğini ve bu kursun kaçıncı tercihi olduğunu görebilmeli." Yapıldı

"Eğitmen kursuna kişi seçerken: kişi başka tercih ettiği bir kursa seçildiyse bunu görebilmeli (hangi kurs ve kaçıncı tercihi olduğunu). kurs eğer kişinin 2. tercihi ise ve bu kişi 1. tercihi olan kurs tarafından seçildiyse, eğitmen o kişiyi seçememeli. Eğer katılımcı 3. tercihi olan kurs tarafından seçildiyse eğitmen onu kursuna seçebilmeli. Seçtiğinde ise kişi 3. tercihi olan eğitmene kişinin 2. tercihine kaydırıldığına dair eposta gönderilmeli." Yapıldı.

"Eğitmen kursuna kişi seçerken: kişi başka tercih ettiği bir kursa seçildiyse bunu görebilmeli (hangi kurs ve kaçıncı tercihi olduğunu). eğer katılımcı 2. ya da 3. tercihi olan kurs tarafından seçildiyse eğitmen onu kursuna seçebilmeli. Seçtiğinde ise kişiyi seçmiş olan eğitmene kişinin 1. tercihine kaydırıldığına dair eposta gönderilmeli." Yapıdı.
