### ISSUE TITLE
Şablon metinlerinin veritabanına taşınması ve yönetim arayüzünden değiştirilebilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#122]
Şablon metinleri şu anda Git deposunda dosya olarak bulunuyor.

Bu metinler etkinlikten etkinliğe değişiklik gösterebileceğinden, farklı etkinliklere göre farklı sürümlerinin bulunabilmesi ve içeriklerinin yönetim arayüzünden değiştirilebilmesi gerekiyor.

**Comment by ozgebarbaros** [comment]
sistem üzerinden gönderilen e-posta sayısı arttığı için bu iş zaruri hale geldi o yüzden önceliklendirildi ve tamamlandı.

**Comment by dfisek** [comment]
Yaşasın :)
