### ISSUE TITLE
Yazılımın deploy edilmesi için Jenkins job'u oluşturulması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#126]
Deployment (sunucuda güncelleme) şu anda elle yapılıyor.

Süreç her güncellemede aynı olduğu için adımları çıkarıp Jenkins gibi bir araçla deploy etmek işimizi kolaylaştırır.

**Comment by ozgebarbaros** [comment]
Adımlar şu şekilde:
cd /opt/ab-kurs-kayit
sudo -u nginx git pull origin master
cd abkayit
sudo source venv/venv/bin/activate
sudo python manage.py makemigrations
sudo python manage.py migrate
sudo systemctl reload nginx
(uwsgi için reload scripti yazmadığımdan şimdilik böyle:)
sudo systemctl stop uwsgi
sudo systemctl start uwsgi

**Comment by ozgebarbaros** [comment]
job olusturuldu.
