### ISSUE TITLE
Yönetim panelinde birden fazla kullanıcı listeleme bölümü, tek bir kullanıcı listesinde birleştirilebilir

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#132]
Yönetim panelinde "Kullanıcılar", "Kullanıcı Profilleri", "Kullanıcı Doğrulama" başlıklı üç ayrı kullanıcı listeleme bölümü var. Birbirleriyle kesişen yerleri olduğu gibi, sadece o bölümlerde görülebilen alanlar da var.

One kullanıcı listesi to rule them all daha kullanışlı olabilir.

**Comment by ozgebarbaros** [comment]
birleştirildi.
