### ISSUE TITLE
Yönetim panelinde bir kullanıcının ad soyadının birleşik olarak aranabilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#134]
Şu anda Doruk ya da Fişek olarak arayabiliyoruz ama Doruk Fişek şeklindeki birleşik bir arama boş dönüyor.

Beraber arayabilsek güzel olurdu.

**Comment by ozgebarbaros** [comment]
Ad+Soyad şeklinde arama yapılabilir durumda şuan.
