### ISSUE TITLE
Fotoğraf ekleme alanına dosya boyutu uyarısı eklenmesi

### ISSUE THREAD

**Issue by adilga** [akademikbilisim/ab-kurs-kayit#135]
Fotoğraf eklerken dosya boyutu için bir limit var ama ekleme esnasında/öncesinde uyarı gösterilmiyor. Kullanıcı büyük boyutlu dosya yüklerse nginx'in hata sayfasına yönlendiriyor. Kayıt ekranına bir bilgilendirme notu eklenebilir.

**Comment by ozgebarbaros** [comment]
düzeltildi.
