### ISSUE TITLE
Kişilerin eğitmenlik durumunun etkinlik bazlı işaretlenebilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#136]
Bir kişi bir etkinlikte eğitmenken, diğer bir etkinlikte katılımcı olabilir.

Şu anda bu bilgi kişinin tüm profili için etkili oluyor. Etkinlik bazlı belirlenebilirse güzel olur.

**Comment by ozgebarbaros** [comment]
Kullanıcının eğitmenlik/yetkili eğitmenlik durumu kullanıcı profilinden ayrılıp kursa bağlı hale getirildi (tabi aynı zamanda etkinliğe de bağlı oluyor bu). Aynı etkinlikte bir kursta yetkiliyken bir kursta sadece görebilir olabiliyor. Hatta bir kursta eğitmenken bir kursta kursiyer olabilir.
