### ISSUE TITLE
Admin olan yetkili eğitmenler kurslarına başvuranları göremiyor ve seçim yapamıyorlar

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#139]
Arayüzde ben gözden kaçırmadıysam, seçim süreci başlamadığı için, eğitmenler de eğitimlerine başvuranları ve profillerini inceleyemiyor.

Bunu inceleyebilseler (ama seçim yapamasalar) güzel olurdu.

**Comment by ozgebarbaros** [comment]
aynı anda hem admin olup hem de eğitmen olan kullanıcılarda bu sorun var. normal eğitmenler kendi kurslarına başvuranları görebiliyorlar.

**Comment by ozgebarbaros** [comment]
şu an görebiliyor olman gerekiyor.tekrar kontrol edebilir misin?
ben test ettim yönetici olan kullanıcımı aynı zamanda bir kursa eğitmen olarak atadım katilim/kayit'a tıkladığında karşıma eğitmeni olduğum kursa yapılan başvuranlar geldi.

**Comment by dfisek** [comment]
Evet görebiliyorum. Başlığı da ona göre düzelttim.
