### ISSUE TITLE
Profil formunda hata olusunca konaklama bilgileri kayboluyor

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#14]
http://kayit.ab.org.tr/accounts/profil sayfasinda, bir hata durumunda (ornegin TC dogrulama hatasinda) sayfa yeniden yuklenince formdaki bilgiler hatirlaniyor ancak konaklama tercihleri kayboluyor.

**Comment by ozgebarbaros** [comment]
düzeltildi
