### ISSUE TITLE
Kullanıcılar listesine etkinlik (site?) süzgeci eklenmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#140]
Şu anda kullanıcı listesi alındığında şu anda tüm kayıtlı kullanıcıların listesi alınıyor.

Burada etkinliğe göre süzgeç kullanabilsek (kampa başvuranlar, x etkinliğine başvuranlar, vs) güzel olurdu.

**Comment by ozgebarbaros** [comment]
tüm kullanıcılar listesi sadece aktif etkinliğe başvuru yapmış kişileri gösteriyor. 
bu sayfanın amacı konaklama tercihlerinin listesini almak.
tüm başvurular sayfası da yine aktif etkinliğe yapılan başvuruları gösteriyor.

**Comment by dfisek** [comment]
Yönetici paneli kastetmiştim, açıklayıcı yazamamışım.

**Comment by ozgebarbaros** [comment]
#182

**Comment by Cediddi** [comment]
5f624c0 issue adı yanlış girildi doğrusu bu.
