### ISSUE TITLE
Kullanıcı profilinde ek soruların görülebilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#142]
Kullanıcı profiline girilen bir notun yönetim panelinden düzenlenebilmesi ve silinebilmesi iyi olur.

**Comment by ozgebarbaros** [comment]
Yönetim panelinden "kullanıcı notları" kısmından düzenlenebilir durumda zaten.

**Comment by ozgebarbaros** [comment]
Pardon "Katılımcı Notları" olacak

**Comment by dfisek** [comment]
Görmemişim, o zaman iş kaydı boşa gitmesin :)

**Comment by dfisek** [comment]
Eğitmenin katılımcı seçtiği, başvuranların listelendiği ekranda "detay"a basarak bilgi görüntüleyebiliyorum.

Burada kamp başvuru sorularında sorulanların bazıları (sonradan eklenenler?) ve kursa özgü sorulan sorular yer almıyor.

**Comment by ozgebarbaros** [comment]
Kamp başvurusu için ve kurs için sorulan sorulara verilen cevaplar kullanıcının profilinde görüntülenebilir.
Admin bütün sorulara verilen cevapları görür.
Eğitmen hem kurs bağımsız sorulan sorulara hem kendi kursunun sorularına verilen cevapları görüntüleyebilir.
