### ISSUE TITLE
Güncelleme bilgilendirilmesinde "diff" de gönderilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#146]
Kurslarda bir güncelleme yapıldığında sadece "2 numaralı kursta güncelleme yapılmıştır." bildirimi gidiyor.

Bunun yanı sıra yapılan güncellemenin tam ne olduğu yazılsa güzel olurdu.

**Comment by ozgebarbaros** [comment]
#148 işini yaparken bunu da aradan çıkardım
