### ISSUE TITLE
Katılımcıların isimlerinin ilk harfi büyük olacak biçimde kaydedilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#147]
Şu anda katılımcıların isimleri, kendileri ne şekilde yazarsa o şekilde kaydediliyor. "Doruk Fişek", "Doruk FİŞEK", "DORUK FİŞEK" gibi farklı görünümler mevcut.

Bunları kayıt sırasında ehlileştirip, hepsini "Doruk Fişek" haline getirebilir miyiz?

**Comment by Cediddi** [comment]
@dogukankotan yapılacak iş basit, user modeline pre_save sinyali yazılacak, firstname ve lastname .title() ile büyütülecek. Daha sonra db'yi fixleriz biz.

**Comment by dogukankotan** [comment]
@Cediddi db fixi de yazabilirim.

**Comment by Cediddi** [comment]
@FatihErdem 'in gözüne takılmış, türkçe karakterler için upper/lower düzgün çalışmıyor. O işler için https://github.com/emre/unicode_tr kullanılabilir.

**Comment by FatihErdem** [comment]
@Cediddi haklisin, unicode_tr is gorur gordugum kadariyla.

**Comment by ozgebarbaros** [comment]
@Cediddi @FatihErdem unicode_tr türkçe karakterleri normalize ediyor. biz böyle birşey istemiyoruz. Örneğin ş Ş olmalı S değil. Tc kimlik no doğrulamasını yapamayız yoksa. O yüzden sadece replace('i','İ') demek yeterli. Diğer karakterlerde sorunumuz yok.

**Comment by ozgebarbaros** [comment]
@Cediddi @FatihErdem tamam unicode_tr bahsettiğim şeyi de yapıyormuş. kullanılabilir.

**Comment by dogukankotan** [comment]
Üstüme alıyorum. Fixleyeceğim.

**Comment by ozgebarbaros** [comment]
@dogukankotan ben düzelttim  a88a9f1
