### ISSUE TITLE
Yetkili eğitmen hiçbir değişiklik yapmadan "gönder"e basarsa da güncelleme e-postaları gönderiliyor

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#148]
Katılımcıların listelenip seçildiği ekranda, hiçbir değişiklik yapmadan "Gönder"e basarsa, tüm kurslar için (değişiklik yapılmasa da), değişiklik yapıldı e-postası gönderiliyor ve "Seçimleriniz başarılı bir şekilde kaydedildi." yazısı çıkıyor.

**Comment by dfisek** [comment]
Buna öncelik verebilir miyiz? Seçimleri yapmaya başladık.

**Comment by ozgebarbaros** [comment]
Düzelttim test edebilir misin? @dfisek

**Comment by dfisek** [comment]
Düzelmiş görünüyor. Daha önce birden fazla e-posta da geliyordu, artık tek geliyor.
