### ISSUE TITLE
Kullanıcı listesinde herhangi bir kullanıcının detay profilini görebilsek

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#150]

**Comment by ozgebarbaros** [comment]
@dfisek admin kullanıcısının gördüğü kullanıcı listesi mi?

**Comment by dfisek** [comment]
Evet, admin kullanıcının gördüğü kullanıcı listesini kastetmiştim, tam açıklayıcı yazamamışım.

**Comment by dfisek** [comment]
Pardon işler karıştı, kullanıcı arayüzünde ama "tüm kullanıcılar" listesine basıldığında.

**Comment by ozgebarbaros** [comment]
tüm kullanıcılar listesinden show profile'e tıklayarak kullanıcının detaylı profili görüntülenebilir.
profilde başka görünmesi istenenler için ayrı işler oluşturulur.
