### ISSUE TITLE
Kullanıcı sisteme giriş yaptığında profilinin kontrol edilerek gerekiyorsa uyarı çıkarılması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#151]
Kullanıcının profilinde eksikler varsa (fotoğraf yok, soruların yanıtlanmamış, vs), kullanıcı sisteme login olduğunda ona bir uyarı yazısı çıkaralım.

Şöyle olabilir: "Profilinizde eksikler bulunuyor. Başvurularınızın daha sağlıklı biçimde değerlendirilebilmesi için profilinizdeki eksikleri tamamlamanızı öneriyoruz."

**Comment by ozgebarbaros** [comment]
#182

**Comment by dogukankotan** [comment]
@dfisek validate yapılmayan aslında gerekli olmayan fieldlar için mi bunu yapacağız?

**Comment by ozgebarbaros** [comment]
@dogukankotan profilimi düzgün doldurmuş olsam bile yine bu uyarı çıkıyor.
Örnek senaryo: yabancı uyruklu olup yabancı kimlik no dolu ama tckimlik no boş.
Bu durumda galiba tckimlik no boş olduğu için uyarı çıkıyor olabilir. PR dev branch'i ile birleştirildi ama bu sorun çözüldükten sonra master'a alınacak.

**Comment by ozgebarbaros** [comment]
@dogukankotan uyarı admin panelde de çıkıyor. çıkmamalı.

**Comment by Cediddi** [comment]
django admin de message kütüphanesini kullanıyor, adminde mesaj vermemenin kontrolünü şu şekilde yapabiliriz:

```
if not request.path.startswith(reverse('admin:index')):
    messages.add_message(request, messages.WARNING, "lorem ipsum")
```

**Comment by dogukankotan** [comment]
Tamamdır bakacağım.

**Comment by dogukankotan** [comment]
@Cediddi evet ufak bir çözüm.

**Comment by ozgebarbaros** [comment]
@dogukankotan  07f10b1 ile admin'de uyarı çıkması engellendi ama zorunlu olmayan alanlar için mesela websitesi boş ise uyarı çıkarmaya gerek yok. Ayrıca şu an sorular kontrol edilmiyor. Sorular kullanıcı profilinden ayrı bir modelde tutuluyor. Kullanıcının etkinlik bazlı sorulara cevap verip vermediğini de sorgulamak lazım.

**Comment by dogukankotan** [comment]
@ozgebarbaros Tamam anladım, issue ya bunu sordum zaten zorunlu alanları validate ediyoruz yani kullanıcı sistemi hackleyip o alanı girmek istemezse bir uyarı çıkmayacak bu durumda. Sadece soruları check edebiliriz o zaman değil mi?

**Comment by ozgebarbaros** [comment]
Kullanıcı profilini güncellemeden yeni etkinliğe başvuru yapamıyor.
