### ISSUE TITLE
Kayıt durumu bölümünün başvuru / değerlendirme sürecinde daha bilgilendirici olması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#156]
Başvurular (ve değerlendirme) sürecinde, başvuranlar "kayıt durumu"nu inceledikleri zaman "Kabul edildiğiniz bir kurs bulunmamakta" yazısı ile karşılaşıyorlar. Kendim kontrol etmedim ama bir katılımcıdan gelen bildirime göre başvuru yapmasalar da aynı şekilde gözüküyor.

Onun yerine,
- Katılımcı başvuru yapmadıysa: "Henüz herhangi bir kursa başvuru yapmadınız"
- Başvuru yaptıysa ama henüz başvurular kapanmadıysa: "Başvurunuz için teşekkürler. Değerlendirme sürecinin başlaması için tüm başvuruların tamamlanması beklenmektedir."
- Başvuru yaptıysa ve değerlendirme yapılıyorsa: "Başvurular değerlendirilmektedir. En geç x Temmuz tarihine kadar sonuçları burada görebilirsiniz."
- Başvuru yaptıysa, değerlendirme bitmiş ve herhangi bir kursa yerleşmediyse: İlk turda kabul edilmeyenlere ama her an kabul edilebileceklerine dair yönelik e-posta şablonunun aynen yapıştırılmış halini
- Kampın başlamasına bir günden az zaman kaldıysa ve herhangi bir kursa yerleşmediyse: Herhangi bir kursa yerleşmediği ve gelecek sene başvurusunu tekrar beklediğimizi belirten e-posta şablonunun aynen yapıştırılmış halini

göstersek, daha bilgilendirici olabilir.

**Comment by dfisek** [comment]
Bu detaylarda gösterilen yazıları nereden değiştirebiliyoruz?

**Comment by ozgebarbaros** [comment]
İş aciliyet teşkil ettiği için bu mesajlar kodun içerisinde.
