### ISSUE TITLE
Başka etkinliğe katılanın başka kursu onaylanmış görünüyor

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#157]
AB 2016'da bir kursa katılmış kişinin başka tercihi onaylanmış gibi renklendiriyor.

Bunun için yapılan sorgunun etkinliğe özgü yapılması, eski etkinlikleri hesaba katmaması gerekiyor.

**Comment by ozgebarbaros** [comment]
düzeltildi.

**Comment by dfisek** [comment]
Sorun hala devam ediyor görünüyor.

**Comment by ozgebarbaros** [comment]
@dfisek sorun farklıydı düzelttim onu da.
