### ISSUE TITLE
Güncelleme bilgilendirmesinde biraz daha fazla bilgilendirme olması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#159]
"1 numaralı kurs" yerine "Linux Sistem Yönetimi - 1 kursu" yazsa, onaylanan (ya da onayı kaldırılan) tercihin kullanıcının kaçıncı tercihi olduğunu yazsa; çok mu masraflı olur? :)

**Comment by ozgebarbaros** [comment]
inform_about_changes şablonunu bu bilgileri de içerecek şekilde güncelledim.
