### ISSUE TITLE
showuser yetkilendirme bugi

### ISSUE THREAD

**Issue by beydogan** [akademikbilisim/ab-kurs-kayit#163]
Normal giris yapmis bir kullanici(**egitmen degil**)  `Detayli kullanici bilgileri` sayfasina urlden erisebiliyor. Idleri degistirerek tum kullanici profillerine de erisilebilir.

Egitmen yetkisi olan kullanici erismeye calisirken  500 hatasi aliyor.

Ornek link: https://kayit.linux.org.tr/accounts/showuser/3689/23681

**Comment by ozgebarbaros** [comment]
@beydogan tekrar deneyebilir misin?

**Comment by ozgebarbaros** [comment]
500 hatası da düzeltildi.

**Comment by beydogan** [comment]
@ozgebarbaros evet ikisi de duzelmis gorunuyor su an, tesekkurler.
