### ISSUE TITLE
Katılımcı profilinde doğum tarihi, iş ve cinsiyetin de gösterilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#165]
Doğum tarihi, iş ve cinsiyet bilgisini alıyoruz ama eğitmenlere profilde göstermiyoruz. Gösterelim. Doğum tarihi olarak yıl yeterli (ya da yaş olarak convert edilmesi de olur).

**Comment by ozgebarbaros** [comment]
profilde doğum tarihi iş ve cinsiyet görünüyor şuan.
