### ISSUE TITLE
Geçmiş etkinliklerin yoklamalarının import edilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#168]
Elde 2012-2015 yılları arasında yoklama kayıtları var. Bunları sisteme import edersek, kullanıcı profilinde yoklama bilgilerini de görebiliriz.

**Comment by dfisek** [comment]
Bu senekilerin de aynı şekilde import edilmesi gerekiyor.

**Comment by Cediddi** [comment]
@dfisek Yoklamalar mevcut lakin kayıt formlarındaki epostalar olmadan kullanıcıları açamıyoruz. Eğer kayıt formlarına erişimimiz olursa (sadece kabul edilenler de yeterli) ben tek tek kullanıcı bilgileriyle eşleyip yoklamaları geçiririm.

**Comment by ozgebarbaros** [comment]
geçmiş etkinliklerin yoklamaları eklendi.
