### ISSUE TITLE
Kontrol panelindeki kursların gruplanması

### ISSUE THREAD

**Issue by yasarcelep** [akademikbilisim/ab-kurs-kayit#171]
Yönetici panelinde, bütün kurs başvuruları listelendiğinden performans sıkıntısı doğuyor. Ayrıca bütün başvuruların sınırlandırılmadan tek sayfada yayınlanmasının da kullanışlı olmadığını düşünüyorum. 

Yönetici panelinde, kurs başvurularını kurslara göre ayırılması ve her kursta belli sayıda sorgu gösterilmesi(sayfada gösterilecek sorgu sayısını değiştirebilir olursak çok güzel olur) bi' nebze de olsa sorunları çözebilir.

**Comment by dfisek** [comment]
Yaşar'ın demek istediği kontrol panel. Böyle bir ihtiyaca özellikle tüm sınıflara yetkili eğitmen olarak atanan staff grubundaki insanlar sahip. Çünkü seçim yapan eğitmenler tek bir eğitimin başvurularını gördükleri için görece kısa bir liste alıyorlar. Staff olanlar tüm kursların tüm başvurularını aynı anda listeledikleri için binlerce satırlık bir liste yükleniyor ve seçim çok zorlaşıyor.

Checkbox'larla seçip kaldırabilsek, gruplayabilsek, tablara bölebilsek, vs vs bir şekilde kullanışlılığı arttırsak güzel olur.

**Comment by ozgebarbaros** [comment]
kontrol panel iyileştirildi. Eğitmen önce hangi eğitim için işlem yapmak istediğini seçiyor sonra katılımcıları listeliyor.
Bir eğitmen bir eğitim için yetkili iken diğer eğitim için yetkili olmayan bir eğitmen olabilir. İki durumda gördükleri ekran farklı oluyor.
