### ISSUE TITLE
Eğitmen Bilgileri'nde varış tarihinden önceki bir tarihte ayrılış tarihi belirtilebilmesi 

### ISSUE THREAD

**Issue by yasarcelep** [akademikbilisim/ab-kurs-kayit#173]
Eğitmen bilgileri'nde belirttiğiniz varış tarihinden önceki bir tarihe ayrılış tarihi belirtip, bunu başarılı bir şekilde kaydedebiliyoruz.

**Comment by ozgebarbaros** [comment]
719ebaf düzeltilmiş
