### ISSUE TITLE
Bir katılımcının başvurusu iptal edildiğinde katılımcıya da bilgi gitmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#174]
Şu anda gitmiyor. Biz iptal ettiğimizde de haberdar olsalar (nedeni ile beraber) iyi olurdu.

**Comment by ozgebarbaros** [comment]
#182

**Comment by Cediddi** [comment]
Eğitmene giden epostanın aynısı mı, yoksa yeni bir taslak ile mi?

**Comment by dfisek** [comment]
Aynısı olabilir. Yalnız neden bilgisi olmalı. Neden bilgisinin eğitmene de gitmesinde bir sakınca yok. Eğitmene giden taslağa da bu bilgi eklenemiyorsa (denemedim), eklenebilmeli.

**Comment by Cediddi** [comment]
Şöyle bir insiyatif aldım, bir eposta kamp-gelismeler + eğitmenlere gidiyor, diğer eposta öğrenciye. Böylece öğrenci eğitmenlerin epostalarını görmüyor. Onun dışında readme'yi de düzelttim {{cancelnote}} eklenebiliyor artık.

**Comment by dfisek** [comment]
Umut'la konuştuk, katılımcıya giden e-posta eğitmene gidenin CC'si mi olsun (yani katılımcı eğitmenin e-posta adresini görsün mü) yoksa ayrı bir e-posta mı olsun dedi; ben de ayrı e-posta olmalı dedim. Eğitmenlerin e-posta adresi bilgisini başvuranlarla paylaşmıyoruz. Eğitime geldikten sonra, kendi e-postasını vermek eğitmenin kendi tasarrufunda.

**Comment by ozgebarbaros** [comment]
add002b yapıldı.
