### ISSUE TITLE
TC kimlik no dogrulama hatasi aldim ancak profilim kaydedildi

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#18]
TC kimlik no dogrulama hatasi aldim ancak sayfayi yenileyince profilimin ve TC kimlik numaramin kaydedilmis oldugunu gordum.

hatayi nasil yineleyebiliriz bilmiyorum.

**Comment by ozgebarbaros** [comment]
TCKimlik no doğrulama hatası alındığında profil kaydedilmiyor. Tam olarak aldığınız hata mesajı neydi? Durumu tekrarlayamıyorsanız kullanıcınızı silsek baştan oluşturup deneme şansınız var mıdır acaba?

**Comment by destan** [comment]
tabi. silin profilimi bir daha deniyeyim: destan {at} kodgemisi.com

**Comment by ozgebarbaros** [comment]
kullanıcınızı sildim. debug mod açık ekrana düşen hatayı bana doğrudan mail atabilirsiniz.

**Comment by destan** [comment]
@ozgebarbaros bu arada epostami onaylamadan giris yapabiliyorum, ayri bir bug acayim mi bunun icin?

**Comment by ozgebarbaros** [comment]
giriş yapabilirsiniz ama profil oluşturamazsınız. profil oluşturamayınca da hiç bir işlem yapamıyorsunuz kursa başvurmak gibi. onaylamadan profil oluşturabiliyor musunuz?

**Comment by destan** [comment]
@ozgebarbaros evet sonra onu farkettigim icin sildim yorumu, dogrulamadan kurs secemedim.

asil bugda ise akis soyle:
1. adi soyadi tcyi yazip kucuk bir yanlislik yaparak (ornegin addan sonra bosluk birak)  post et ancak konaklama girme
2. hata al 
   ![image](https://cloud.githubusercontent.com/assets/442813/12051036/5a8e9b70-af06-11e5-9044-14bc63d15ca7.png)
3. sonra dogru olarak yaz, ancak yine konaklama girme, hata alma
4. sayfada devam etmek icin profilinizi tamamlamaniz gerek der, bu asamada tckimlik no dahil hersey formda dolu yalnizca, konaklama bilgileri eksik
5. konaklama tercihi ekle, post et
6. `2. adimdaki hatayi` yine alirsin, ancak profil doldurulmus durumda
7. profil sayfasini refresh edince profilin tam dolu oldugunu gor. `Profilinizi aşağıda güncelleyebilirsiniz` yazisini gor

**Comment by ozgebarbaros** [comment]
kod aslında davranması gerektiği gibi davranıyor ama hata mesajları kafa karıştırıcı olmuş.Düzeltildi.
