### ISSUE TITLE
COMMON_CONFIG_FILE'da ne olmalı?

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#180]
COMMON_CONFIG_FILE değişkeninde referans verilen ayar dosyasında nelerin bulunması gerektiğine dair döküman eksikliği var. Birinin o dosyada nelerin olması gerektiği ya da olabildiğini readme'de belirtmesi yeni kurulumlar ve kurup PR atmak için çok iyi olacaktır.

**Comment by ozgebarbaros** [comment]
Bunlar wiki'de yazıyor: https://github.com/akademikbilisim/ab-kurs-kayit/wiki/Yap%C4%B1land%C4%B1rma-Dosyas%C4%B1---%C4%B0lk-kurulumda-dikkat-edilmesi-gerekenler

**Comment by Cediddi** [comment]
O zaman issue'yu dökümantasyonun elden geçmesi ve genişletilmesi olarak değiştirebiliriz, ya da yeni bir issue açabilirim?

**Comment by ozgebarbaros** [comment]
@Cediddi dökümantasyon kısmı daha çok yeni kurulum yapacaklar tarafından yazılsa, yani kurulum için dokümanı açıp eksik olan kısımları tespit edildikçe dokümana katkı verilse süper olur.
#182 işi için ilk adım zaten kendi geliştirme ortamlarının kurulumu olacağı için çalışma ortamlarını kurarken belgede olmayan şeyleri bana soracaklar cevabını Wiki'ye yazanlara ve sonucunda başarılı bir şekilde kurulumu tamamlayanlara çikilata verilir.

**Comment by yasarcelep** [comment]
@Cediddi @ozgebarbaros Ben Wiki'ye müsait oldukça omuz atmayı düşünüyordum. Eğer arkadaşlar isteklilerse neden olmasın? :) Yine de diğer öncelikli noktalara odaklanılması daha doğru olabilir.

**Comment by Cediddi** [comment]
Ben wiki'yi güncelledim, ayar dosyasını da düzgünce açıklamaya çalıştım, readme'ye link koydum. Bu iş kapanmıştır. Wiki'yi geliştirmeye devam.
