### ISSUE TITLE
2016 Python/Django sınıfı için issuelarda ödül avcılığı

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#182]
2016 Python/Django sınıfında bir etkinlik olarak koda destek olmayı düşünüyoruz. Bunun için bazı kolay ve orta seviyedeki issue'lara ödül(bounty) koyabiliriz. Bounty'ler tabiki cüzi, eğitmenlerin karşılayabileceği şeyler olursa iyi olur. Özetle üç ya da dört tag açıp issue'lara atabiliriz (otomat çayı, çikolata, dondurma, ice americano). Böylece öğrenciler bounty hunting'i ve rekabeti ve pr atmayı öğrenir. Öğrenciler bayağı istekli gözüküyor.

**Comment by Cediddi** [comment]
Label ile mi yapalım? Yoksa ben mi bedel biçeyim sınıfta?

**Comment by ozgebarbaros** [comment]
@Cediddi ödül listesi belliyse etiket koyabilirsin.

**Comment by Cediddi** [comment]
Benim yetkim yok

**Comment by ozgebarbaros** [comment]
@Cediddi geldiğimde beraber yaparız o zaman.

**Comment by ozgebarbaros** [comment]
bunu yapmadık.
