### ISSUE TITLE
requirements.txt oluşturulmalı mı?

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#184]
Python paketlerini shell script ile tek tek kurmak yerine `pip install -r requirements.txt` çözümünü kullansak daha doğru bir çözüm olur bence. requirements.txt python projelerinde bağlılık yönetiminin defacto standardı. Bazı IDE ve editörler requirements.txt ile entegre bile oluyor (Pycharm Community mesela)

**Comment by ozgebarbaros** [comment]
@Cediddi bence hazırlayalım. bi pull requestini alırım;)

**Comment by Cediddi** [comment]
#182

**Comment by ozgebarbaros** [comment]
687e17d olusturulmus
