### ISSUE TITLE
CharField'ın max_length'i int olmalı

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#185]
max_length normalde bir integer olmalı, ama sanırım postgresql str olduğunda kendi içinde cast edebilmiş. Fakat django'nun validator'ları elimde patladı.

`File "/home/cediddi/.venv/ab-kurs-kayit/lib/python3.4/site-packages/django/core/validators.py", line 329, in <lambda>
    compare = lambda self, a, b: a > b
TypeError: unorderable types: int() > str()`

Django 1.10'da bu problemi Warning vererek  çözmüşler.
Detaylı bilgi = https://code.djangoproject.com/ticket/24818

**Comment by ozgebarbaros** [comment]
#181 bu sorun python3'e geçiş ile alakalı olabilir. Python2.7 de böyle bir hata almıyorduk.

**Comment by Cediddi** [comment]
Doğrudur, bende zaten onunla uğraşıyorum. Genellikle max ve min gibi length'leri de hep int kullanırdım, ilk defa başıma gelince araştırdım. dökümanlar int mi str mi belirtmiyor ama örnekler hep int.

**Comment by Cediddi** [comment]
Problemi çözdüm. Python2'nin bir dizayn hatası ve bu issue 2 için de geçerli bir problemi çözüyor. Eğer iki farklı tür > < operasyonu yapacaksa ve __gt__ veya __lt__ methodları belirli değilse otomatik olarak türleri karşılaştırılıyor. Dolayısıyla "255" > 256 True dönüyor. Bu da filtreleri geçersiz hale getiriyor. 3 bu problemi hata vererek çözmüş.

**Comment by ozgebarbaros** [comment]
b8e73bb düzeltilmiş
