### ISSUE TITLE
Seçim yapmayan eğitmenlerin katılım/kayıt ekranının oluşturulması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#188]
Seçim yapmayan bir eğitim katılım/kayıta tıkladığı zaman, sadece eğitime seçilmiş katılımcıların bir listesini görecek.

Bu listede şu kolonlar yer alacak: Başvuru No, İsim, Soyisim ve Detay Linki

Detaya tıklandığında, katılımcının fotoğrafı görülecek ve eğitmenin not girebileceği bir düz metin alan olacak. Eğitmen bu şekilde istediği kadar not ekleyebilecek.

**Comment by dfisek** [comment]
Eğitmenin katılımcıyı potansiyel eğitmen olarak da işaretleyebilmesi gerekir (#111 ile beraber).

**Comment by ozgebarbaros** [comment]
Seçim yapamayan eğitmen, katılımcıları potansiyel eğitmen olarak işaretleyebiliyor, not ekleyebiliyor, kendi ekledikleri notları görebiliyorlar.
