### ISSUE TITLE
parola degistirince logout oluyorum

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#19]
parola degistirince logout oluyorum, bu zaten beklenen bir durum olabilir ancak kullanici acisindan kafa karistirici. kullaniciyi logine yonlendirerek cozulebilir belki.

**Comment by ozgebarbaros** [comment]
Login ekranımız anasayfa:) O sebeple oraya yönleniyor. Logout olduktan sonraki mesajı ona göre daha açıklayıcı yapabiliriz.

**Comment by ackepenek** [comment]
@destan "parola değiştirince logout oluyorum" tam olarak ne demek? nasıl bir akış gerçekleştirdiniz. Normalde login durumda parolanızı değiştirdiğiniz size parolanız değiştirildiğine dair uyarı çıkıp kaldıgınız yerden devam edebiliyor olmalısınız. Problemi ve tekrarlama durumunu açıklayabilir misiniz?

**Comment by destan** [comment]
"parola değiştirince logout oluyorum" soyle demek:
1. login olup parola degistir
2. parolaniz degistirildi mesajini gordukten sonra profil sayfasina git
3. profilinizi goremiyorsunuz cunku logout edilmissiniz
