### ISSUE TITLE
Katılımcının şehir bilgisinin düz metin yerine liste olması ve oradan seçilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#191]
Şu anda bu bilgiler düz metin bulunduğu için üzerinde işlem yapılması zor oluyor.

**Comment by Cediddi** [comment]
Sadece Türkiye için mi? Yoksa global mi? Parametreye bakıyor.

**Comment by ozgebarbaros** [comment]
sadece tr şehirleri eklendi. kullanıcı profil sayfasinda şehirler dropdown listeden seçiliyor artık.
