### ISSUE TITLE
Etkinliklere son evrak kabul tarihi eklenmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#194]
Kabulleri için evrak gönderecek kişilerin evraklarını göndermeleri beklenen son tarihin sistem tarafından bilinebilmesi.

**Comment by Cediddi** [comment]
Bu bilgiyi etkinlik oluştururken tanımlayabileceksiniz lakin bu bilgi #195 dışında nerelerde kullanılacak? Kullanıcıya gösterilecek mi? Eposta template'lerinde bulunacak mı? Ve en önemlisi birden fazla son kabul tarihi eklenebilecek mi?

**Comment by ozgebarbaros** [comment]
eklendi
