### ISSUE TITLE
Etkinlik bazlı olarak evrak istenip istenmeyeceğinin seçilebilmesi

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#196]
Bazı etkinliklerde katılımcıların kabulü için ek evrak istenirken (ör: kamp), bazıları için istenmeyebilir (ör: AB Kursları).

**Comment by ozgebarbaros** [comment]
bu özellik eklendi.
yönetim panelinden site modelinde evrak gerekli olarak işaretlenmesi gerekiyor.
