### ISSUE TITLE
Etkinlik bazlı profil oluşturulması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#199]
- Kullanıcı genel profilinde yer alan "Başvuru yapabilir mi?" alanının etkinlik (site) bazlı profile taşınması
- Kullanıcı genel profilinde yer alan "Evrak gerekli" alanının etkinlik (site) bazlı profile taşınması
- Kullanıcı genel profili ile ilişkili olan belgelerin, etkinliklerle ilişkilendirilmesi
- Kullanıcı etkinlik profiline kullanıcı profili güncel mi alanı eklenmesi

**Comment by ozgebarbaros** [comment]
#200 işinin yapılabilmesi için bunun yapılması gerekiyor. Kişi x etkinliğine başvurabilmesi için profilini güncellemeli bunu da etkinlik bazlı profildeki can_apply değişkeniyle yapacagiz. kişi profilini güncellediğinde can_apply true olarak ayarlanır. Tabi yeni oluşturulan kullanıcı profilleri için can_apply
true yapılmalı.

**Comment by ozgebarbaros** [comment]
kullanıcı profil ekranı bir miktar karışık olduğu için bu işi üzerime alıyorum

**Comment by ozgebarbaros** [comment]
Etkinlik bazlı profile şunlar eklendi:
"""
Kullanıcı genel profilinde yer alan "Başvuru yapabilir mi?" alanının etkinlik (site) bazlı profile taşınması
Kullanıcı genel profilinde yer alan "Evrak gerekli" alanının etkinlik (site) bazlı profile taşınması
Kullanıcı genel profili ile ilişkili olan belgelerin, etkinliklerle ilişkilendirilmesi
Kullanıcı etkinlik profiline kullanıcı profili güncel mi alanı eklenmesi
"""
- öğrenci evrak ekleyebiliyor (eğer etkinlik için evrak gerekliyse)
- eğitmen potansiyel eğitmen olarak işaretleyebiliyor.
- admin hepsini yapabiliyor.
