### ISSUE TITLE
Basvuru sayfasina gidis daha kolay olabilir

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#20]
http://kayit.ab.org.tr/egitim/applytocourse sayfasina gitmek icin sag ustteki menuyu kullanmak bazi kullanicilar icin cok `intuitive` olmayabilir.

sonucta bu eylem sistemin temel amaci oldugundan, anasayfaya `basvuru yap` gibi bir dugme konularak `http://kayit.ab.org.tr/egitim/applytocourse` sayfasina bir kisayol verilebilir.

**Comment by ozgebarbaros** [comment]
Sol taraftaki menuden Katılım/Kayıt bağlantısından da gidilebiliyor.

**Comment by ackepenek** [comment]
Katılım/Kayıt menüsü:

Anonim kullanıcı için;
Yeni kullanıcı oluşturma

Giriş yapmış kullanıcı için;
Kurs Başvurusu Yapma

Kurs başvurusunu yapmak için profil oluşturma zorunluluğu olduğu için giriş yaptıktan Katılım/Kayıt'a tıklayan bir kullanıcının kullanıcı profili yoksa profil oluşturma sayfasına yönleniyor.  Profili olan bir kullanıcı için Katılım/Kayıt tercih sayfası olarak kullanılıyor.

Eğer gerekli görünürse aşağıdakinen benzer bir yapı yapılabilir
Katılım/Kayıt'a tıklayan birisi Profili yoksa, tercih sayfasına gelsin. Ancak uyarı ile profilinizi oluşturmalısınız desin. Ve profil oluşturacagı bir düğme yerleştirelim. Bu daha dogru olur.

Bu işi kapatıyorum

**Comment by fyarci** [comment]
selamlar

girilen bilgilerin sonundaki bosluklari silmek gerekiyor sanirim bir bosluk yuzunden uzun sure hata aldim. ayrica is ve organizasyon seceneklerine aciklama getirmek daha guzel olabilir.  ayrica formu doldurma esnasinda yanlis yapildiginda konaklama seceneklerini cinsiyete gore filtrelenmiyor. emeginiz icin ellerinize saglik cok guzel olmus. 

Best Regards
Fatih N. YARCI
fatihyarci.com.tr
