### ISSUE TITLE
Kullanıcı yeni bir etkinliğe başvuracağı zaman, kullanıcı profil güncellemesi yaptırılması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#200]
Kullanıcının profilde değişen bilgileri olabilir. Profile yeni eklenmiş sorular olabilir.

Yeni yapılan bir başvuruda, kullanıcıya profilini bir güncelletelim.

**Comment by dogukankotan** [comment]
Profile yeni bir soru eklenirse ve boş olursa #231 ile uyarıyı gösteriyoruz.

**Comment by ozgebarbaros** [comment]
bunu yapıyoruz
