### ISSUE TITLE
Clientip hatası

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#201]
Sitede garip garip yerlerde bu hatayı almaktayım. Birşeyi eksik mi yaptım, yoksa çözülmesi mi gerek?

`Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: 'clientip'`

**Comment by ozgebarbaros** [comment]
bu loglama ile ilgili bir hata. settings.py içerisinde log formatına bakarsan clientip ve user diye iki parametre istiyoruz (bu bizim log formatına eklediğimiz parametreler). bazı yerlerde django loga birşeyler yazmak istiyor ama yazmaya çalıştığı şeyin içerisinde clientip yok o yüzden bu hatayı veriyor.
düzeltilse hoş olur ama önemli değil.

**Comment by Cediddi** [comment]
Evet, test etmek için onu formattan kaldırdım fakat başka bir problemin hâlâ devam ediyor, ayrı bir issue açacağım.

**Comment by ozgebarbaros** [comment]
sorunun clientip log formatından silinmeden çözülmesi gerekiyor. çünkü o bilgiye log'da ihtiyacımız var. yani işlemi yapan kullanıcı ve onun IP bilgisi loglarda olmalı.

**Comment by Cediddi** [comment]
Şimdi şöyle bir çözüm buldum. clientip sadece django ve db'de yok, keza onlarda sadece konsola loglanmış. Dolayısıyla dosyaya yazılanlarda clientip var, konsola yazılanlarda yok, bende ona güvenerekten django ve db hataları için ikinci bir formatter yazdım.

**Comment by ozgebarbaros** [comment]
çözülmüş
