### ISSUE TITLE
kurs secimi sayfasi bos gelmeyebilir

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#21]
kurs secimi sayfasi ilk acildiginda en azindan 1 tercih inputu kullanici icin otomatik eklenmis gelse daha iyi olabilir. cunku zaten kullanici en azindan 1 kurs sececek, bir tane input her durumda olmali.

**Comment by ackepenek** [comment]
Aşağıdaki durumlar nedeniyle tercih ekleme butonuna bagımlı yaptım:

1- Hiç kurs tercihi seçmemişse bu ekrandan belli olmalı
2- Kurs tercihi seçti daha sonra tüm tercihlerini silmek istedi. bu ekran boş gözükmeli ve 1. durumla aynı ekran olmalı.(hiç seçmemiş gibi)

şimdilik wonfix'e çekiyorum.

**Comment by ackepenek** [comment]
bu işi kapatıyorum.
