### ISSUE TITLE
Javascript kodlarının elden geçmesi

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#212]
Yapılacak işler:
- Öğrencilerle ilgili tabloların javascript kodları içinden çıkılmaz ve genişletilemez bir durumda. Bazı yerlerde DataTables'in eski bazılarında yeni api'si kullanılmış.
- Çoğu yerde callbackler kodu anlaması zor hale getiriyor, callback cehennemi olmaya giden yerler var.
- 3. parti kodlarla bizim kodlarımız iç içe, hangisi ney anlamak zor, vendorlar klasörlenmeli
- Bazı dosyalar minified, bazıları değil, bazıları ikisi de(?). Herşey açık olur, sunarken minify ederiz.
- Bazı kodlar html'e entegre durumda, js dosyalarına bölünmesi gerekiyor
- Semantik isimlendirme şart. Ayrıca yapılan hacklerin dökümente edilmesi gerekiyor.

**Comment by Cediddi** [comment]
@monrcelik gönüllü olduğunu söylemişti js ve css konularına. Önce js'ye bakabilirse, işlev görünümden daha kritik.

**Comment by ozgebarbaros** [comment]
commit 916ea9883d71ef30eea93805755e909932d7fe53  bu iş ile ilgili
