### ISSUE TITLE
Öğrenci not alanının textarea yapılması, sınırlandırılması ve sınırının bildirilmesi

### ISSUE THREAD

**Issue by ugurarici** [akademikbilisim/ab-kurs-kayit#218]
Front-end tarafında gereken bir düzenleme.

Öğrenci detay sayfasında (başvuru detayı olarak da geçiyor olabilir) öğrenciye not eklendiğimiz alan şu an tek satırlık bir input. Öncelikle bunun textarea şeklinde çok satırlı girdi alanına çevrilmesi. Ardından bu alana en fazla 500 karakter girilebileceği için ön yüzde bu şekilde sınırlandırılması ve sınırdan ve kalan karakter kullanım hakkından kullanıcının bilgilendirilmesi.

Yani: textarea altına kalan karakter sayısını bildirmek için **500** yazıp kullanıcı yazdıkça her karakterde bu sayının düşmesini sağlarsak yeterli olacaktır.

**Comment by Cediddi** [comment]
Hallettim, PR'ı var #223

**Comment by ozgebarbaros** [comment]
bir kaç eksik var. yetkili olmayan eğitmen sayfasında da aynı sorun var onları düzeltip öyle merge edicem.

**Comment by ozgebarbaros** [comment]
düzeltildi
