### ISSUE TITLE
Profil güncellerken "TC NO" sorunsalı

### ISSUE THREAD

**Issue by om3rcitak** [akademikbilisim/ab-kurs-kayit#219]
accounts/profil sayfasından profilimi güncellemeye çalışırken "\* Bu TC Kimlik numarasına sahip başka hesap var." hatası alıyorum.

muhtemelen database'de "bu tc var ise bu hata ver" gibi bir kod var arkaplanda. o kodun "veritabanında 1den fazla var ise ve o tc profili güncelleyen kişiye ait değil ise" gibi birşey olmadı gerekiyor.

ben yinede bunun için kendim pull-request göndermeye çalışacağım. ama beceremezsem sana assigned etmiş olurum :)

**Comment by ozgebarbaros** [comment]
bunu kontrol ediyoruz zaten başka bir sorun olabilir. iki farklı hesabın olabilir mi?

**Comment by om3rcitak** [comment]
benim bildiğim ve kullandığım tek hesabım var. istersen yinede bi database den check et. 
Ha şunu da söyliyim; belki alakası vardır. Profil güncellerken mail adresimi de güncellemeye çalıştım. Eğer kontroller mail adresine göre yaıplıyor ise ondan da kaynaklanıyor olabilir.

**Comment by ozgebarbaros** [comment]
evet sorun buradan kaynaklanıyor:)

**Comment by om3rcitak** [comment]
şimdi farkettim, mail adresim güncellenmiş. mail dışındaki diğer alanlar güncellenmemiş. böylede garip bir durum var

**Comment by ozgebarbaros** [comment]
senin iki tane hesabın var sistemde biri linux.org.tr ile bitiyor diğeri omercitak.net domain'li ilk zamanlar tc kimlik no'nun sistemde var olup olmadığını kontrol etmiyorduk. hangisini sileyim?

**Comment by om3rcitak** [comment]
@omercitak.net i silebilirsin

**Comment by ozgebarbaros** [comment]
sildim
