### ISSUE TITLE
Anket sonuçlarında tüm eğitmenler için verilen cevapları görebiliyorum

### ISSUE THREAD

**Issue by beydogan** [akademikbilisim/ab-kurs-kayit#228]
Ruby on Rails sınıfının eğitmeni olmama rağmen tüm anket sonuçlarını görüntüleyebiliyorum. 

Kayıtlı olduğum eposta: mehmet.beydogan@gmail.com

**Comment by beydogan** [comment]
Telegramdaki mesajı yeni okudum @Cediddi sanırım bug değil featuremış bu olay :)

**Comment by ozgebarbaros** [comment]
bunun hata değil özellik olduğuna ikna olduysak kapatıyorum bu işi:)
