### ISSUE TITLE
Geliştirme ortamından migration dizininin silinmesi ve .gitignore'a eklenmesi

### ISSUE THREAD

**Issue by dogukankotan** [akademikbilisim/ab-kurs-kayit#230]
Migrationlar migrate edilirken applerin sıralamaları yanlış olduğundan ProgrammingError gerçekleşiyor.

django.db.utils.ProgrammingError: relation "abkayit_site" does not exist gibi

Sıfırdan kurulum yapıp deneyen olursa güzel olur.

**Comment by dogukankotan** [comment]
Örnek olarak:

Abkayit migrate edilirken training'e ihtiyaç duyuyor. Ama Tranining migrate edilmediğinde ProgrammingError ortaya çıkıyor

**Comment by Cediddi** [comment]
Django otomatik sırayı yönetiyor. Problem dev de migration olmasında. Master daki migrationlar doğru ama dev de yarım yamalak migrationlar olunca djangonun kafası karışıyor.

**Comment by ozgebarbaros** [comment]
@Cediddi @dogukankotan işin adını değiştirdim;)

**Comment by Cediddi** [comment]
Bu sırada bu işi yine master ve dev'e doğrudan atmam gerekecek. Sen de pr'ları vs. merge ederken migrationların eklenmediğini kontrol etmelisin Özge abla.
