### ISSUE TITLE
Testteki kurs saatleri 

### ISSUE THREAD

**Issue by sinansh** [akademikbilisim/ab-kurs-kayit#239]
Kurs kayıt sistemindeki testte bulunan soru : 

_13. Kursta dersler günün hangi saatlerinde?
a-10:00-12:00, 14:00-16:00, 17:00-19:00
b- 09:30-12:30, 14:00-17:30, 19:00-21:30
c-08:00-12:00, 13:00-17:00, 18:00-22:00
d- 09:00-12:00, 14:00-17:00_

SSS sayfasındaki cevap :  
_Kurs saatleri, 09:30-12:30, 14:00-18:00 şeklindedir. Bazı eğitmenler akşamları etüd yapabilir._

burası küçük bir kafa karışıklığı oluşturuyor. SSS'yi okuyan ilk önce B şıkkını işaretleyecektir. Sistem doğru cevap olarak D şıkkını kabul ettiği için D şıkkının değerleri düzeltilebilir.

**Comment by ozgebarbaros** [comment]
D şıkkının değerleri düzeltildi. Doğru cevap 09:30-12:30, 14:00-18:00.
