### ISSUE TITLE
Sıkça sorulan sorular sayfası eklenmesi.

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#24]
İçeriğinin hazırlanıp admin panel'den eklenmesi

**Comment by ozgebarbaros** [comment]
SSS sayfası menu olarak eklenip kamp'ın sitesindeki sıkça sorulan sorulara link verildi. Ama SSS testi yapabilmek için admin sayfasından soruları çoktan seçmeli cevaplar ile eklemek gerekiyor.

**Comment by dfisek** [comment]
Bu işin hala açık olması gerekiyor mu?

**Comment by ozgebarbaros** [comment]
gerekmiyor
