### ISSUE TITLE
Egitmenlerin istatistik bilgilerine erişmesi

### ISSUE THREAD

**Issue by ackepenek** [akademikbilisim/ab-kurs-kayit#240]
Eğitmenler kurs bazlı, il bazlı, üniversite bazlı istatistik bilgilerine erişebilmeli.

**Comment by ozgebarbaros** [comment]
İstatistik sayfasındaki eksikler:
- Kurs bazlı (bu veri şu an hiç görünmüyor), 
- Şehir bazlı (bunu da göstermiyor), 
- Üniversite bazlı  (büyükten küçüğe sıralı olsa güzel olur.) başvuran kişi sayısı

**Comment by ackepenek** [comment]
Üniversite bazlı sıralamayı bulmak kolay olsun diye #47 işiyle alfabetik yapmıştım.

**Comment by ozgebarbaros** [comment]
UserProfile modeli değişti. is_student diye bir field yok artık. O yüzden şu sorgu artık geçersiz: UserProfile.objects.filter(is_student=True).values('university').annotate(Count('university')).order_by('university') Bir de bu sorgu bize sistemdeki bütün kullanıcı profillerini getiriyor. Aktif etkinlikteki trainesscourserecord kayıtlarından universite bazlı sayılara erişmek gerekiyor. Bu sayılar template'e iletiliyor zaten ama sadece sıralanması lazım.

**Comment by ackepenek** [comment]
- [x] Kurs bazlı (bu veri şu an hiç görünmüyor),
- [x] Şehir bazlı (bunu da göstermiyor),
- [x] Üniversite bazlı (büyükten küçüğe sıralı olsa güzel olur.) başvuran kişi sayısı

pr: #242
