### ISSUE TITLE
sayfaya bir eposta adresi koyalım

### ISSUE THREAD

**Issue by nyucel** [akademikbilisim/ab-kurs-kayit#241]
Bir problemle karşılaşan kullanıcılar ne yapacaklarını bilemiyorlar. Özelden bize yazmaları yerine sorunbildir@ab.org.tr gibi bir adres var diye yazarsak oraya ulaşabilirler belki.

**Comment by ackepenek** [comment]
https://kayit.ab.org.tr anasayfasına bu uyarı yerleştirildi.
