### ISSUE TITLE
Kullanıcı profilinde geçmiş etkinliklerin bilgisinin yer alması

### ISSUE THREAD

**Issue by dfisek** [akademikbilisim/ab-kurs-kayit#243]
Şu anda kullanıcı profillerinde, sadece o kullanıcının katıldığı etkinlikle ilgili girilmiş bir not varsa görülüyor. Bir not yoksa, o kullanıcının o etkinliğe katıldığına dair hiçbir bilgi görünmüyor.

Hem kullanıcının daha önce katıldığı etkinliklerin, hem de o etkinliklerdeki yoklama durumunun gösterilmesi gerekli. Yoklama durumu "Katılım yüzdesi" gibi bir yüzdesel rakamla gösterilip, gerektiğinde o yüzdeye tıklanıp detayının görülmesi gibi kurgulanabilir.

Bu özelliğin AB 2017 kurs kabulleri başlamadan önce yapılması gerekiyor ki, eğitmenler katılımcı seçerken sağlıklı değerlendirme yapabilsin.

**Comment by ozgebarbaros** [comment]
Katılımcının daha önce başvuru yaptığı etkinlikler ve kabul edildiği kurs varsa katılım oranı kullanıcı profilinde görünür hale getirildi.
