### ISSUE TITLE
kullanıcı profilinde yer alan şehirlerin tekilleştirilmesi

### ISSUE THREAD

**Issue by ackepenek** [akademikbilisim/ab-kurs-kayit#244]
Zamanında kullanıcılar aynı şehirleri farklı ifadelerle girebilmişler bu nedenle bir karışıklık ortaya çıkmış. 
Şuan profil ekranında şehir seçimi için bir liste verildiği için sorun yok ama önceki kayıtların tekilleştirilmesi gerekiyor.

Örnek:
```
Afyonkarahisar
Afyon
```
```
Sanliurfa
ŞANLIURFA
```

**Comment by ozgebarbaros** [comment]
Bu sorun @ackepenek yazdığı betik ile düzeltildi.
