### ISSUE TITLE
Sıkça Sorulan Sorular sayfasını sisteme dahil edelim

### ISSUE THREAD

**Issue by nyucel** [akademikbilisim/ab-kurs-kayit#247]
Sıkça Sorulan Sorular sayfasını sisteme dahil edersek hem başvuru ile aynı adresten ulaşılabilir hem de ekleme/düzeltme yapabiliriz.

**Comment by dfisek** [comment]
Başvuru ile aynı adresten zaten ulaşılabiliyor, sayfayı etkinliğin web sitesindeki "Sık Sorulan Sorular" sayfasına yönlendiriyoruz.

Sayfaya zaten etkinliğin web sitesinden ekleme-düzeltme yapılabiliyor.
