### ISSUE TITLE
Onaylanmış katılımcının unchecked gelmesi

### ISSUE THREAD

**Issue by om3rcitak** [akademikbilisim/ab-kurs-kayit#248]
Selam,

kursa başvuranları görüntülediğimiz sayfada (https://kayit.ab.org.tr/egitim/controlpanel/{course_id}/) onayladığımız kişiler background'ı yeşil olarak geliyor ama "Onayla" checkbox ı unchecked geliyor.

**Comment by ozgebarbaros** [comment]
merhaba,

örnek bir kullanıcıyı bana özelden yazabilir misin?

**Comment by ozgebarbaros** [comment]
bu sorun tekrar etmediği için kapatıyorum
