### ISSUE TITLE
Sistemin Debug Moddan Çıkması - SSL Sertifikalarının Yüklenmesi

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#25]

**Comment by ozgebarbaros** [comment]
ve https'e geçilmesi
http'den https'e yönlendirme koyulması
http üzerinden yapılan yayının durdurulması
gerekiyor.

**Comment by ackepenek** [comment]
ssl sertifikaları yükledim, http -> https yönlendirmesini(301) yaptım
