### ISSUE TITLE
"Tüm Başvurularımı İptal Et" tüm eğitmenlere mail gitmesi

### ISSUE THREAD

**Issue by om3rcitak** [akademikbilisim/ab-kurs-kayit#252]
Selam,

Bir katılımcı "Tüm Başvurularımı İptal Et" butonuna bastığında doğrudan tüm eğitmenlere mail gidiyor. bunun yerine iptal eden kişinin kabul edildiği kursun hocalarına mail gitse daha güzel olur diye düşündüm.

**Comment by ozgebarbaros** [comment]
Aslında tüm eğitmenlere mail gitmeyecek şekilde yaptık ama bazı iptaller tüm eğitmenlere gidiyor. Düzelttim.

**Comment by ackepenek** [comment]
Aslında problem tamamen https://github.com/akademikbilisim/ab-kurs-kayit/blob/076541fe4a083049e2458f51f2585ea0255230ef/abkayit/training/tutils.py#L381  atamalarından kaynaklanıyor. 

`context['recipientlist']`, `REPORT_RECIPIENT_LIST` değişkeninin bulunduğu bellek bölgesine referans veriyor.  `context['recipientlist']` değişkeniyle yapılacak her işlemler aynı bellek bölgesini kullanıyor. Dolayısıyla `context['recipientlist']`; view'in ortak değişkeniymiş gibi haraket ediyor.  Kurslar iptal edildikçe o kursun eğitmeni ekleniyor listeye.

Bence, belirttiğim satırdaki`context['recipientlist'] = REPORT_RECIPIENT_LIST` ifadesi yerine `context['recipientlist'] = []` ifadesi kullanılıp, `context['recipientlist'] = REPORT_RECIPIENT_LIST + approvedpref[0].course.authorized_trainer.all().values_list('user__username', flat=True)` denilse,  REPORT_RECIPIENT_LIST içerisindeki adresi alıcı listesinden kaybetmemiş olurduk


ornek: https://jeffknupp.com/blog/2012/11/13/is-python-callbyvalue-or-callbyreference-neither/

**Comment by ozgebarbaros** [comment]
@ackepenek bu sekilde duzeltip commit edebilirsin;)

**Comment by ackepenek** [comment]
@ozgebarbaros kısmet
