### ISSUE TITLE
Sorulara verilen cevaplarda js injection

### ISSUE THREAD

**Issue by Cediddi** [akademikbilisim/ab-kurs-kayit#261]
Katılımcılardan biri cevap olarak script tag'i içinde alert(1) yazmış ve çalışıyor. Yani cevaplar gösterilirken bir hata yapılmakta. safe olarak işaretlenmiş olabilirler...

**Comment by ozgebarbaros** [comment]
sorun cevapların gösterildiği html bölümünü templatetag'den doğrudan sayfaya basıyor olmaktan kaynaklanıyordu. assignment_tag'e çevirip html içerisinde html'i render edecek hale getirince sorun düzeldi.
