### ISSUE TITLE
Neden GPL V3 değil de GPL V2 ?

### ISSUE THREAD

**Issue by ghost** [akademikbilisim/ab-kurs-kayit#262]
Neden GPL V3 değil de GPL V2 ?

**Comment by onurguzel** [comment]
Neden AGPLv3 değil de GPLv3?

**Comment by ghost** [comment]
Sistemin Server-Side tarafıda kullanıma ve geliştirilmeye açık bundan
kaynaklı GPLv3 Kullanılması daha mantıklıdır

2017-07-27 17:16 GMT+03:00 Onur Güzel <notifications@github.com>:

**Comment by Cediddi** [comment]
Henüz gplv3 kullanmıyoruz batuhan. Agplv3 te bir seçenek. Ben v3 uyumlu olduğu sürece okeyim.
