### ISSUE TITLE
form alanındaki boşlukların kontrol edilmesi ve silinmesi

### ISSUE THREAD

**Issue by ackepenek** [akademikbilisim/ab-kurs-kayit#27]
selamlar

girilen bilgilerin sonundaki bosluklari silmek gerekiyor sanirim bir bosluk yuzunden uzun sure hata aldim. ayrica is ve organizasyon seceneklerine aciklama getirmek daha guzel olabilir.  ayrica formu doldurma esnasinda yanlis yapildiginda konaklama seceneklerini cinsiyete gore filtrelenmiyor. emeginiz icin ellerinize saglik cok guzel olmus.

Best Regards
Fatih N. YARCI
fatihyarci.com.tr

**Comment by ozgebarbaros** [comment]
isim ve soyisimdeki boşluklar tckimlik no doğrulamasını etkiliyor baştaki ve sondaki boşluklar kaldırılarak doğrulama yapılır hale getirildi.
