### ISSUE TITLE
formdaki bosluklar tckn dogrulamasini engelliyor

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#28]
https://github.com/akademikbilisim/ab-kurs-kayit/issues/20#issuecomment-167989569 yorumda da belirtildigi gibi ad soyad alaninda basta/sonda bosluk olursa tckn dogrulamasi basarisiz oluyor.

**Comment by ozgebarbaros** [comment]
düzeltildi.
