### ISSUE TITLE
bazen profilimi guncellerken ekteki hatayi aliyorum

### ISSUE THREAD

**Issue by destan** [akademikbilisim/ab-kurs-kayit#29]
[IntegrityError at _accounts_profil.html.zip](https://github.com/akademikbilisim/ab-kurs-kayit/files/74850/IntegrityError.at._accounts_profil.html.zip)

**Comment by ozgebarbaros** [comment]
bu hatayı ben de tekrarladım. uç bir durum ve sayfayı baştan yüklemek sorunu çözdüğü için sadece hata mesajını düzeltmekle yetiniyorum.
