### ISSUE TITLE
Parola yenileme ve degistirme

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#3]
Parola yenileme ve degistirme (parolamı unuttum sayfası)

**Comment by ackepenek** [comment]
Kullanıcı parolasını unuttuysa; email adresi bekleniyor. email adresi sistemde kayıtlı ise parola değiştirme linki gonderiliyor. linke tıklandıgında parola değiştirme ekranı acılıyor.

Aynı zamanda sisteme giriş yapmıs kullanıcı parolasını değiştirebilmektedir.
