### ISSUE TITLE
Kayit sonrasi onay e-postasi

### ISSUE THREAD

**Issue by hdogan** [akademikbilisim/ab-kurs-kayit#37]
Kayit olduktan sonra onay e-posta mesaji gelmiyor diye bir iki ogrenciden e-posta aldim.

**Comment by ozgebarbaros** [comment]
Kontrol edebilmemiz için hangi e-posta adresleri ile kayıt olmaya çalıştıklarını bilmemiz gerekiyor. Siz biliyorsanız bize e-posta ile gönderebilir misiniz?

**Comment by hdogan** [comment]
Kesin emin degilim fakat birisi erdal_ayan [at] yahoo [nokta] com olabilir.

**Comment by ozgebarbaros** [comment]
Bu sorun yahoo.com uzantılı e-posta adreslerinde yaşanıyor. ilgileniyoruz.

**Comment by ozgebarbaros** [comment]
düzeltildi.
