### ISSUE TITLE
Başvuru günü saati eklenmeli.

### ISSUE THREAD

**Issue by GulsahKose** [akademikbilisim/ab-kurs-kayit#39]
Sanıyorum ki başvurular yapıldığı sırayla sıralanıyor. Eğer öyle sıralanmıyorsa kursa seçilecek kişileri kolaylaştırması açısından başvuru günü saati biligisi eklenmesi faydalı olacaktır.

**Comment by ozgebarbaros** [comment]
Başvurular yapıldığı sıraya göre sıralanıyor. Başvuru numarası küçük olan önce başvurmuş anlamına geliyor. Saat bilgisi eklenmesine gerek yok
