### ISSUE TITLE
başvuru geri çekme

### ISSUE THREAD

**Issue by nyucel** [akademikbilisim/ab-kurs-kayit#40]
Kurslar için başvuru yapanlar çeşitli nedenlerle başvurularını geri çekmek isteyebiliyorlar. Onlara teker teker kurslardan başvurularını silmek yerine bir "başvurumu iptal et" seçeneği sunabilirsek iyi olur. Bu seçeneğe tıkladıklarında bu işlemi geri alamayacaklarını ve bütün başvurularının silineceğini söylemeliyiz tabi. hatta bir mail atıp ondaki linke tıklamalarını bile isteyebiliriz çok uğraştırmayacaksa.

**Comment by ackepenek** [comment]
@nyucel Hocam,
- Şimdilik başvuru iptal için epostaya link gönderme işine girmeyelim derim.
- Başvuru Sayfasında "Tüm Başvurularımı İptal Et" seçeneği ekleyebiliriz.
- Kurs Tercih Dönemi Bittiğinde bu iptal sürecini de yapamayacaklar.(İstenirse anaysayfaya duyuru da ekleyebilriz tercih dönemi içerisinde kurs başvurusu yapılabilir veya iptal edilebilir şeklinde)

**Comment by nyucel** [comment]
bu seçeneğin eklenmesi iyi olur bence. eposta olmasa bile kullanıcıyı uyaralım da kazara iptal etmesinlar başvurularını ;)

**Comment by ozgebarbaros** [comment]
Kurs tercihleri kapandığında sadece Başvuru İptal butonunun kalması ve bir uyarının bulunması iyi olabilir.

**Comment by ackepenek** [comment]
kırmızı ile uyarırız :)

**Comment by ackepenek** [comment]
İş yapıldı ekran görüntüsü:

![image](https://cloud.githubusercontent.com/assets/1234305/12089913/61308642-b2f2-11e5-9787-10cc630cc41d.png)
