### ISSUE TITLE
Kontenjanı dolan kurslar

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#41]
Bunlara başvuruyu pasifleştirmek gerekiyor. Kurs listesinde de bu kursun kontenjanı dolu uyarısı çıkmalı

**Comment by ackepenek** [comment]
- Kursiyerleri homejen dagıtmak adına mantıklı(tek bir kursa yıgılma olmaması için)
- Egitmenlere kurs basvuru dönemi içinde kendi kursunun basvurularını açabilir, kapatabilir

**Comment by ackepenek** [comment]
Eğer tüm kursların basvuru tarihi geçmişse kursiyer aşağıdaki gibi görüyor:
(sistemde toplam 3 tane kurs varken)
![image](https://cloud.githubusercontent.com/assets/1234305/12101898/f0364636-b33f-11e5-9372-7a96c1bcf04f.png)

Basvurular açıkken kontenjan durumuna göre egitmen kendi kursunun basvurusunu basvurulara kapatabiliyor:
![image](https://cloud.githubusercontent.com/assets/1234305/12101913/20231a04-b340-11e5-9a54-fd8ee6468ae0.png)

Basşvurular açıkken bir tane kurs basvurulara kapatılmıssa kursiyer aşağıdaki gibi görüyor:

![image](https://cloud.githubusercontent.com/assets/1234305/12101925/3c9a5328-b340-11e5-89de-afc31f7bff18.png)
