### ISSUE TITLE
Ek bilgiler alanı her satıra bir kelime olarak görüntüleniyor.

### ISSUE THREAD

**Issue by GulsahKose** [akademikbilisim/ab-kurs-kayit#42]
![abkayit](https://cloud.githubusercontent.com/assets/2954981/12090445/b06b8f40-b2f7-11e5-84ae-81647dc8bfe0.png)

**Comment by ackepenek** [comment]
@GulsahKose nasıl görünmesi gerekiyor?

**Comment by GulsahKose** [comment]
En azından satırlar bu sütunun genişliği kadar uzamalı bence. Çünkü "ekibi" "için" kelimeleri bir satıra sığar. Böyle okuması daha kolay olur.

**Comment by MuhammetDilmac** [comment]
Demo panel ve bilgiler varsa girip hata nedenine bakmak isterim mümkün müdür?

**Comment by ackepenek** [comment]
Ekran görüntüsündeki gibi hale dönüştürüldü:

![image](https://cloud.githubusercontent.com/assets/1234305/12104470/59390d30-b354-11e5-970a-49202752faf5.png)

**Comment by GulsahKose** [comment]
Elinize sağlık
