### ISSUE TITLE
Sistem Kayıt Sırasında Yabancı Uyrukluların T.C. kimlik numarasını kabul etmiyor.

### ISSUE THREAD

**Issue by garayli** [akademikbilisim/ab-kurs-kayit#44]
Kayıt sırasında önümüze çıkan ilk sayfada isim, soyisim, mail adresi ves. gibi önemli olan bilgileri girdikten sonra sistem T.C. tarafından bana verilen numarayı kabul etmiyor.

**Comment by ozgebarbaros** [comment]
Yabanci kimlik no alanina numarayi yazip tc kimlik numarasi alanini bos birakmaniz gerekiyor. Ulke alaninda da ulkenizi belirtmeniz gerekli

**Comment by ackepenek** [comment]
Türkiye dışında başka ülke seçilirse Yabancı Kimlik No alanı doldurulmalı. Türkiye seçilirse TC Kimlik No doldurulmalı.

Bu alanlar ülke seçimine göre zorunludur.

Şuan bir hata olmaması lazım. wontfix'e cekip kapatıyorum
