### ISSUE TITLE
Kayıt onay epostasında link hatası

### ISSUE THREAD

**Issue by ebayer** [akademikbilisim/ab-kurs-kayit#45]
Kayıt onay epostasında gelen linkin başında protokol olmadığı için eposta istemci link olarak göstermiyor. Örneğin bana gelen onay metni şöyle:

Hesabınız ile ilgili işlemlere devam edebilmek için aşağıdaki linke tıklayarak hesabınızı aktif etmelisiniz.
kayit.ab.org.tr/accounts/active/done/....

**Comment by ackepenek** [comment]
Bu düzeltildi
