### ISSUE TITLE
Profil formunda hatalı mesaj

### ISSUE THREAD

**Issue by ebayer** [akademikbilisim/ab-kurs-kayit#46]
Profil formunu ilk defa doldururken cinsiyet seçince konaklama tercihlerinin güncellenmesi gerektiği ile ilgili uyarı metni gösteriliyor.

**Comment by ackepenek** [comment]
Bu özelliğin kursiyer profilinde olan kişiler için olması bir özellik. 
Sadece kursiyerde konaklama seçeneği seçilmişse ve cinsiyet değiştirildiğinde konaklama seçenekleri ile ilgili uyarı vermesi ve önceki sçeiminin ekrandan ona göre düzenlenmesi gerekiyor.
Ancak aşağıdaki düzenleme yapılacak:
- Egitmenlerin profilinde konaklama seçenekleri çıkmadığı için bu uyarı egitmenler için verilmemesi gerekiyor.
- Kursiyer hiçbir konaklama seçenegi seçmemişse cinsiyet seçeneği değiştirdiğinde böyle bir uyarı vermemesi gerekiyor
