### ISSUE TITLE
Eğitmenler katılımcıların diğer tercihlerinide görebilsin

### ISSUE THREAD

**Issue by ugorur** [akademikbilisim/ab-kurs-kayit#49]
Katılımcıların diğer tercihlerini görebilmek hem seçim yaparken tercih sebebi hem de diğer eğitmenler ile iletişim kurmamıza yardımcı olur.

**Comment by ackepenek** [comment]
Başka kurs tarafından onaylanmışsa kursiyerin bilgisinin bulundugu satır kırmızı ve detayında da hangi kurs tarafından onayandıgı bilgisi var artık

![image](https://cloud.githubusercontent.com/assets/1234305/12144505/c34e1b1a-b490-11e5-93a2-2a7d8e3f6de0.png)

**Comment by ugorur** [comment]
kirmizi olamdan da gorebilmemiz daha iyi olur. diger kurs hocasi ile onaylamadan once gorusmek icin.

**Comment by ackepenek** [comment]
İsteğinizi gerceklestirdim- onaylanmadan da kursiyerin sectigi diger kurslar gorunuyor artık: Akşamdan sonra kayit.ab.org.tr'de gorunur.

![image](https://cloud.githubusercontent.com/assets/1234305/12144838/23305c94-b493-11e5-858b-4f159d2e9e2a.png)
