### ISSUE TITLE
Basvuru reddetme

### ISSUE THREAD

**Issue by FatihErdem** [akademikbilisim/ab-kurs-kayit#51]
Eger basvurulari kabul etmenin yaninda reddetme gibi bir imkan olursa guzel olur. 

Ornegin kursa 1. tercihi olarak basvurmus kisiyi reddettim. Bu diger basvurdugu kurslara da yansirsa diger kursun egitmenleri onu artik "zaten 1. tercihi var secilme ihtimali yuksek" gibi dusunmek yerine secime dahil edebilirler. Eger haberleri olmazsa 2. ve 3. tercih secilebilecek kisiler degerlendirmeye bile alinmamasina sebep olabilir.

**Comment by ozgebarbaros** [comment]
reddedilen başvurular başvuru süresi dolduğunda diğer eğitmenlere görünecek.

**Comment by ozgebarbaros** [comment]
Bu sorunu 1. 2. ve 3. tercih değerlendirmelerini farklı zamanlarda yaparak çözdük.
