### ISSUE TITLE
Kara liste

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#54]
eğitmen kendi kursunun seçenlerle ilgili not düşsün, kara listeye alabilsin.(userprofile modeline blacklisted: True/False alanı ve blacklist_note alanları eklenmesi gerekiyor. control_panelde detaya tıklandığında görünebilir.)

**Comment by ackepenek** [comment]
not bilgisi sadece kara liste için mi var detaylandırmak gerekiyor. şimdilik karmaşık düşünmeyerek her katılımcıya ait; katılımcıyı onaylayan eğitmenlerin girebileceği bir durum bilgisi (Gelmedi-Kara Listede, Geldi) ve not düşebilecekleri bir alan ekleyecegim.

Bu alanları katılımcı kesin onaylandıktan sonra görülebiiyor ve düzenlenebiliniyor olarak yapacagım.

**Comment by ackepenek** [comment]
Kursiyerleri onaylama işlemi bittikten sonra yani egitmenleri 3. tercihleri de seçtikten sonra aşağıdaki not ve durum alanları aktif oluyor ve kursiyere burada not düşebiliniyor:

![image](https://cloud.githubusercontent.com/assets/1234305/12222518/78f31fae-b7c7-11e5-8af3-40a07432fe2b.png)

**Comment by ackepenek** [comment]
tarayıcılar javascript kaynaklarını önbellekte tuttugu için tarayıcıda js kaynaklarını yenilemek gerekiyor(ctrl-R gibi) .kullanıcılara bunu yaptıramayız bu nedenle javascript dosyaları için diger yöntemleri hayata geçirmek lazım. vakit olursa..
