### ISSUE TITLE
Kursa kabul edilenler icin teyit sayfasi.

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#59]
Önceden mail ile yapılıyordu bunun sistemden yapılması daha kullanışlı olacaktır.

**Comment by ackepenek** [comment]
Kursiyerin seçildiği dersi teyit etme sayfası  aşağıdaki gibi oldu:

![onayla1](https://cloud.githubusercontent.com/assets/1234305/12225082/800e135a-b80a-11e5-9e2e-250e1115dafb.png)

![onayla2](https://cloud.githubusercontent.com/assets/1234305/12225084/8743dcfe-b80a-11e5-90a8-0ad8344ce3ba.png)

Eğitmen onaylarsa ve kursiyer de teyit ederse bu sayfa aşağıdaki gibi görünüyor.

![onayla3](https://cloud.githubusercontent.com/assets/1234305/12225085/9c3fe382-b80a-11e5-9a3a-9e918ef354a4.png)

Eğer kursiyer herhangibir dönemde egitmen tarafından onaylanmamıssa aşağıdaki gibi görünebiliyor:
![onayla4](https://cloud.githubusercontent.com/assets/1234305/12225086/af48b3be-b80a-11e5-935a-cc9703b2a13d.png)
