### ISSUE TITLE
Kursiyer başvurusunu iptal ettiğinde eğitmene mail gitsin

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#66]

**Comment by ackepenek** [comment]
Eğitmenler gereksiz mail almasın diye şöyle bir kısıt koydum: 

eğitmen onay baslangıç süresinden kursiyer teyit bitme süresi arasında "Tüm Tercihlerimi İptal" et butonuna tıklanırsa kursun  eğitmenlerine email bilgilendirmesi yapılıyor

**Comment by ackepenek** [comment]
Aşağıdaki gibi mesaj gidiyor:

![image](https://cloud.githubusercontent.com/assets/1234305/12342091/b1b12b7c-bb2f-11e5-8ca3-dd7f21c48211.png)

Bu iş devreye alındı
