### ISSUE TITLE
yeni tercihlerin alınması

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#70]
- onaylanmamış veya onaylanıp da teyit edilmemiş kayıtlar silinecek.
- 1 tercih hakkı ile tercihleri tekrar açılacak.
- Mustafa hocanın söyleyeceği kurslar haricindekileri kontenjan doldu diye işaretlenmesi.
- tercih yapan herkes ön tanımlı olarak egitmen onayından geçmiş olarak kaydedilecek.
- tekrar teyid istemeyeceğiz. geleceklerini teyid etmiş gibi olacaklar.
- daha önceden onaylanmış ve teyid etmiş kişilere tercih ekranı görünmemeli.(su an zaten gorunmuyor ama bundan emin olalım:))

**Comment by ackepenek** [comment]
@ozgebarbaros teyit işlemini kacırmıs olanlara mı bu ek tercih imkanı tanıyacagız yoksa sisteme yeni üye olan birisi de bu işlemi gerçekleştirebilir mi? Ona göre geliştirme yapacagım.

**Comment by ozgebarbaros** [comment]
@ackepenek bir tercih yapıp da onaylanmış ve teyid etmiş kişiler haricinde herkese açacağız. amacımız kontenjanı az olan kurslara katılımı arttırmak.

**Comment by ozgebarbaros** [comment]
@ackepenek yani bir geliştirme yapmaya gerek yok.

**Comment by ackepenek** [comment]
@ozgebarbaros tamamdır.

**Comment by ozgebarbaros** [comment]
@ackepenek şu ikisi geliştirme istiyor (geçici bir geliştirme)
tercih yapan herkes ön tanımlı olarak egitmen onayından geçmiş olarak kaydedilecek.
tekrar teyid istemeyeceğiz. geleceklerini teyid etmiş gibi olacaklar.

**Comment by ackepenek** [comment]
Geliştirme şu şekilde:
- İstenilen kurs ek tercihe acılıp kapanabilir. (Kurs modelinde basvurulara acık mı gibi bir seçenek var)
- Site modelinde ek tercihlerin hangi tarihler arasında yapılacagı hangi tarihler arasında onaylanacagı var(normal tercihlerdeki gibi)
- Kursiyer tercih sayfasında eğer teyit ettiği bir kurs yok ise ek tercih alanını görecek ve "ek tercih ekle" butonu ile 1 tane tercih ekleyebilecek.
- Eğitmen eğer ek tercih kabul ediyorsa onaylama dönemi içerisinde ek tercihleri onaylayabilecek.

birçok durumu test etmeye calistim, bu kafayla görebildiğim bir problem yok gibi..
deploy ediyorum.

**Comment by ackepenek** [comment]
Geleceği kesinleşen kursiyerler dısındaki kursiyerlere teyit ekrarnı aşağıdaki gibi gorunmektedir suanda:

![image](https://cloud.githubusercontent.com/assets/1234305/12472061/d985c5e0-c00c-11e5-9a9b-6a3d3759ae05.png)

Ek tercih zamanı geldiğinde ilgili buton arayuzde otomatik gorunecek ve 1 tane ek tercih yapma hakkına sahip olacak.

**Comment by ozgebarbaros** [comment]
@ackepenek ek tercihler alınırken eski tercihlerin silinmesi gerekiyor.

**Comment by ackepenek** [comment]
@ozgebarbaros buna neden ihtiyac var. Neden kişinnin diğer tercihlerini silme ihtiyacı duyuyorum. Zaten onaylı ve teyitli olmayan birisi tercih yapabiliyor.

@ozgebarbaros bir kişi birden fazla kursta teyitli ise bu ayrı bir bug, onu bulup öyle çözmek gerekiyor.

**Comment by ozgebarbaros** [comment]
@ackepenek 1. sebep normalde 1. 2. 3. tercih döneminde tercihler değiştirilirken eski kayıtları silip baştan oluşturuyoruz zaten burada da yapabiliriz.
2. sebep ek tercih döneminde eski kayıtların hiç bir hükmü kalmıyor. Db'de yer kaplamasına gerek yok.
3. sebep 1. 2. 3. tercih döneminde başka bir kursa onaylanmışsa (teyit değil eğitmen onayı) ve ek tercihte onaylanmışsa kursiyerin ekranı sapıtıyor. 
4. sebep  1. 2. 3. tercih döneminde onaylanmışsa, ek tercih döneminde de onaylanmışsa ve teyit edilmişse duplicate kayıtlar oluşuyor.
Bu sorunları tek tek çözmektense eski kayıtları silmek daha pratik bir çözüm.
@ackepenek silmenin bize getireceği bir sorun var mı?

**Comment by ackepenek** [comment]
@ozgebarbaros db de gereksiz yer kaplama dısında digerlerini zaten sagliyorum.

**Comment by ozgebarbaros** [comment]
@ackepenek peki kalsın öyleyse.

**Comment by ackepenek** [comment]
bu geliştirme - istenileni karşıladı.
işi kapatıyorum.
