### ISSUE TITLE
kabul edilenlerle ilgili istatistikler

### ISSUE THREAD

**Issue by nyucel** [akademikbilisim/ab-kurs-kayit#75]
Başvuruda bulunanlarla ilgili istatistiklerin benzerleri de kabul edilenlerle ilgili olsa çok güzel olur. İlave olarak başvuruda bulunan kadın ve erkeklerin yüzde kaçını kabul ettik görebilsek de iyi olur.

**Comment by ackepenek** [comment]
Geliştirmeyi yaptım.

Şuan aşağıdaki istatistikler görülebilir:
- kurs bazında hangi tercih sırasında kaç başvurus var
- kurs bazında teyit edenlerin sayısı(eğitmen onayladı ve kursiyer geleceğini teyit etti)
- üniversite bazında başvuranların sayısı
- üniversite bazında teyit edenlerin sayısı
  -toplam profil, toplam tercih ve toplam teyit eden sayısı
- kadın/erkek bazında başvuru yüzdesi
- kadın/erkek bazında teyit yüzdesi

İşin statusunu bitti olarak değiştirdim. Başka isteğin olup olmamasına göre kapatılabilir

**Comment by ackepenek** [comment]
işi kapatıyorum.
