### ISSUE TITLE
istatistiklere kurslara katılanların bilgisinin eklenmesi

### ISSUE THREAD

**Issue by nyucel** [akademikbilisim/ab-kurs-kayit#76]
Her kurs için başvuran, kabul edilen, geleceğini teyit eden ve gelenleri bir arada göstren bir istatistik eklense çok iyi olur

**Comment by ackepenek** [comment]
![image](https://cloud.githubusercontent.com/assets/1234305/12883855/3441b6c4-ce63-11e5-8cc8-a1e31c069180.png)

Hızlı olması açısından ekran görüntüsündeki gibi bir istatistik yaptım. Şimdilik idare eder diye düşünüyorum. Ekran görüntüsündeki işaretlediğim alandaki butonlara tıklayarak istenilen istatistiğin grafikte aktif veya devre dışı olmasını sağlayabilirsiniz.

**Comment by nyucel** [comment]
iyileştirme için teşekkür ederim. teyit edenlerle kurslara gelenler aynı şey olmamalı gibi geliyor bana. 

kurslara gelenleri eğitmenlerin geldi diye onayladığı sayıyı alasak daha iyi olur bence.

**Comment by ackepenek** [comment]
Toplam Tercih: Kursa herhangi bir tercih sırasında tercih edenlerin toplam sayısı
Toplam Kabul: Eğitmenlerin kendi kursu için seçtiği toplam sayı
Toplam Teyit(Gelenler): Eğitmenler seçimi yaptıktan sonra kursa hak kazanan kursiyerlerin kesin geleceğim diye işaretlemiş(teyit etmiş) olanların sayısı

Bu şekilde gösterim yapılıyor. Toplan Teyit sayısı gelenleri işaret etmiş oluyor gibi, yine de isterseniz değişikliği yaparım

**Comment by ackepenek** [comment]
Şimdi anladım. Onu da ayrı çizgide gösterelim. (Kimler kesin geldi.)

**Comment by ackepenek** [comment]
Güncelllemeyi gerçekleştirdim.

Tercih sırasına bağlı istatistik varsayılan olarak devre dışı geliyor artık yer kaplamaması için

Eğitmenlerin portal üzerinden aldığı yoklamada eğer yoklama alınmaz ise varsayılan olarak "Geldi" şeklinde işaretlemede yapmıştık. Bu istatistik okunurken bunun göz önünde bulundurulmasında fayda var. Bu nedenle eğitmenlerin gelenler veya gelmeyenler için yapacağı işlemler önemli.

**Comment by ackepenek** [comment]
ek bir durum çıkmadığı için işi kapatıyorum.
