### ISSUE TITLE
Kullanıcılar kurslar için n adet başvuru yapabilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#79]
Kullanıclar kurslar içn 3 tercih yapabilmeli. Kullanıcı tercihleri, tercihler dondurulana kadar değişebilimelidir.

**Comment by ozgebarbaros** [comment]
Kullanıcılar settings.py içerisinde PREFERENCE_LIMIT değişkenine atanan değer kadar tercih yapabiliyorlar. Admin panelden her bir tercih için ayrı onaylama başlangıç ve bitiş tarihi belirlenebiliyor (hem egitmen onaylama, hem de sonrasında kursiyer teyit için. teyit özelliğini kapatmak için settings.py'den REQUIRE_TRAINESS_APPROVE değerini False yapmak gerekiyor.).
Ek tercih şansı verilmek istenirse ADDITION_PREFERENCE_LIMIT değişkenine istenilen sayıda ek tercih şansı verilebilir. Ek tercihler için de ayrı ayrı onaylama başlangıç ve bitiş tarihleri belirlenebiliyor. (preference_order eksi (-) ile başlayanların ek tercih olduğunu anlıyoruz. )
