### ISSUE TITLE
Tercihlerin yönetim panelinden dondurulabilmesi gerek

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#81]
Tercihlerin yönetim panelinden dondurulabilmesi gerek. Yetkinli kullanıcı haricinde kimse değiştirememeli.

**Comment by ozgebarbaros** [comment]
Tercihler yönetim panelinden dondurulabilir. Hatta tek tek kurs bazında da yapılabilir.
