### ISSUE TITLE
 Başvuran kişi başvurusunu çekebilmeli.

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#82]
Başvuran kişi başvurusunu çekebilmeli.

**Comment by ozgebarbaros** [comment]
başvuru yapan kişi başvuru tarihi bitimine kadar tercihlerini istediği gibi değiştirip iptal edebilir. tercihler bitip kurs başlayana kadar istediği zaman tercihlerini iptal edebilir.
