### ISSUE TITLE
Kabuller yapıldıktan sonra "Kabul Edildi" epostasının gitmesi gerek.

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#83]

**Comment by ozgebarbaros** [comment]
1. Kabul e-postası gönderilenler üzerinde değişiklik yapılamıyor. (kişi kendi başvurusunu iptal edebilir journal'a not düşülüyor)
2. 1. tercihi kabul edilenlere eğitmen istediği zaman e-posta
      gönderebilir. (Eğitmenin ekranına kabul e-postalarını gönder diye bir
      buton koyulur )
3. Diyelim ki eğitmen bu butona tıklamadı ve kullanıcılara bildirim
   gönderilmedi. Toplu halde bir bildirim onay tarihi bitiminde yapılacak (cron)
4. Diğer (2. 3.) tercihlerine kabul edilenlere eğitmenlerin onay tarihi bitiminde e-posta gönderilecek (cron)
5. 25 Temmuz - 4 Ağustos arasında (eğitmen onaylama
   tarihi bitimiyle, kampın başlangıç tarihi arası), isteyen eğitmen,
   kaçıncı tercihi olduğuna bakmaksızın (2. ya da 3. tercihi bile olsa)
   doğrudan kabul edebilir ve kabul e-postası gönderilebilir.

Bu 5. durumdaki dönemde bir "toplu onay" tarihi olmadığından,
eğitmenlerin "kabul e-postası gönder"e basmayı unuttuğu ama listesine
eklediği adamlara o dönemde her gün saat 08:00'de (örneğin), kabul edilen ama
e-posta gönderilmeyen herkese e-posta gönderilmesi. Bunun dezavantajı
saatlerin bile önemli olduğu bir zamanda gecikmeli gönderim. Ama sadece
eğitmen kabul e-postası göndertmediğinde oluyor. (cronjob)

---

Ayrıca seçilmemiş kişilere:

1) Eğitmen onaylama tarihi bitiminde, "seçilmemiş" kişilere toplu
gönderilecek bir e-posta. Ayrı bir şablon: "İlk anda seçilmediniz ama
bekleyin anacım, her an seçilebilirsiniz, e-postanızı ve web'i kontrol
edin" diyecek bişi. (cronjob)

2) Kamp başlangıç tarihinde "seçilmemiş" kişilere toplu gönderilecek
bir e-posta. (cronjob)

**Comment by ozgebarbaros** [comment]
Cronjob tanımları Site modelinde yapılan her değişiklik sonrasında eskileri silinip yenileri oluşturuluyor.
Bu işin sonunda 3 tip e-posta metni oluştu fonksiyon isimleri şu şekilde:
send_consent_email, not_approved_trainess_after_approval_period_ends, not_approved_trainess_eventstardate bunlar için örnek metinler README içerisinde var. Yönetici panelinden tanımlamaların yapılması gerekiyor.
