### ISSUE TITLE
Kullanıcı profiline yorum yapılabilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#84]
Kullanıcın profilinde alt alta istenilen kadar entry girilebilmeli ve bunun kullanıcı tarafından görülmemesi gerekiyor. Lakin tüm eğitmenler ve yöneticiler tarafından bu entryler görülebiliyor olacaktır. Bunun düzenleme ve silme yetkilerinin yönetici dışında kimsede bulunmaması gerekmektedir.

**Comment by ozgebarbaros** [comment]
Eğitmenler kurslarına kursiyer seçtiği sayfada eğitimden sonra kişiler hakkında yorum girebilir ve onay esnasında da önceki etkinliklerde o kişiler hakkında yazılmış yorumları görebilirler. Admin kullanıcısı yönetim panelinden Trainess Note kısmında kişiler için girilmiş olan yorumları görebilir düzenleyebilir.
