### ISSUE TITLE
Başvuru ardından başvurunun alındığına dair e-posta atılması

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#85]
Başvuran bir kişi başvurduktan sonra kendisini eposta ile başvurusunun alındığı bilgisi gönderilmelidir.

**Comment by ozgebarbaros** [comment]
Kayılımcının başvurusu alındığında ve başvurusunu değiştirdiğinde kendisine e-posta ile bilgilendirme yapılıyor
