### ISSUE TITLE
Kişi tercihlerini değiştirdiği zaman kendisine eposta ile bunun bilgisi gönderilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#86]
Kişi tercihlerini değiştirdiği zaman kendisine eposta ile bunun bilgisis gönderilmelidir.

**Comment by ozgebarbaros** [comment]
Tercih değişikliği esnasında kullanıcıya bilgilendirme amaçlı e-posta gidiyor ancak bu e-postanın içeriğinin etkinliğe göre belirlenmesi gerekiyor. #122 nolu iş bu ihtiyacı karşılayacak.
