### ISSUE TITLE
Tercih yapma işlemi dondurulmadan önce eğitmenler kurslarına katılımcı seçememeliler ve kabul işlemine başlayamamalılar

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#87]
Tercih yapma işlemi dondurulmadan önce eğitmenler kurslarına katılımcı seçememeliler ve kabul işlemine başlayamamalılar.

**Comment by ozgebarbaros** [comment]
Eğitmenlerin hangi tarihler arasında kabul yapabilecekleri admin panelden belirlenebiliyor. Kabul tarihi başvuru bitiş tarihinden bir gün sonraya ayarlanması durumunda kursiyer tercih tarihleri ile eğitmenlerin kabul tarihleri çakışmayacaktır.
