### ISSUE TITLE
Herhangi bir zamanda o ana kadar kurslara başvurmuş herkese eposta gönderilebilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#88]
Herhangi bir zamanda o ana kadar kurslara başvurmuş herkese eposta gönderilebilmeli

**Comment by ozgebarbaros** [comment]
Not olarak buraya düşeyim, mass mailing işleri için iki seçeneğimiz var:
1. önceden belirlediğimiz türde mailman listeleri oluşturup kişileri otomatik uye yapmak veya çıkarmak. (Bu smtp server'ı ağlatmamak, karalisteye girmemek ve karşı taraftan spam olarak algılanmaması için bir seçenek)
2. mailmane alternatif fikir olarak direk https://docs.djangoproject.com/en/1.9/topics/email/#send-mass-mail şunu kullanıp gerisine karışmayabiliriz. Artık smtp server karalisteye mi girer load'u mu artar biz karışmayabiliriz bu işe. O smtp'yi yöneten düşünsün de diyebiliriz.

**Comment by dfisek** [comment]
#89 gerçekleştirildiğinde bu da çözülmüş oluyor.
