### ISSUE TITLE
Kullanici profili görüntüleme ve güncelleme ekranı

### ISSUE THREAD

**Issue by ozgebarbaros** [akademikbilisim/ab-kurs-kayit#9]
Sağ üst köşedeki profil ikonuna tiklandiğinda user profile butonu geliyor. Butona tıklandığında görüntüleme ve güncellenme ekranı eklenmeli bu butona

**Comment by ackepenek** [comment]
Kullanıcının profili yoksa işlem yapabilmesi için profil olusturulması isteniyor. Bu iş kullanlan  view ve template kullanıcının profilinin güncellemesi için de kullanıldı. Sağ üste yer alan menüdeki User Profile butonuna baglandı.
