### ISSUE TITLE
Başvuran kişilerin tamamına ya da bir kısmına eposta gönderilebilmeli - Belirli bir kursa başvurmuş herkes

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#91]
Birden fazla kurs seçilebilmeli (kamp2016-django-basvuranlar)(kamp2016-django-kabul) Course modeline mailman listesinin adresini ekleyebiliriz.

**Comment by dfisek** [comment]
#89 gerçekleştirildiğinde bu da çözülmüş oluyor.
