### ISSUE TITLE
Başvuran kişilerin tamamına ya da bir kısmına eposta gönderilebilmeli - Belirli bir kursa kabul edilen herkes

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#93]
Belirli bir kusra kabul edilen herkes. (birden fazla kurs seçilebilmeli.) (kamp16-django-kabul)

**Comment by dfisek** [comment]
#89 gerçekleştirildiğinde bu da çözülmüş oluyor.
