### ISSUE TITLE
Başvuran kişilerin tamamına ya da bir kısmına eposta gönderilebilmeli - Tüm kabul edilmeyenler

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#94]
Tüm kabul edilmeyenler (kamp16-django-kabuledilmeyenler) (Bir kişi başvurduğunda tüm kabul edilmeyenlere eklenecek, kişi kabul edildiği zaman bu listeden çıkarılacak ve kabul edilenlere eklenecek.)

**Comment by dfisek** [comment]
#89 gerçekleştirildiğinde bu da çözülmüş oluyor.
