### ISSUE TITLE
Başvuran kişilerin tamamına ya da bir kısmına eposta gönderilebilmeli - Belirli bir kursa kabul edilmeyen herkes

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#95]
Belirli bir kursa kabul edilmeyen herkes. (birden fazla kurs seçilebilmeli.) (Kişi kabul edildiğinde bu listeden çıkarılacak.)

**Comment by dfisek** [comment]
#89 gerçekleştirildiğinde bu da çözülmüş oluyor.
