### ISSUE TITLE
Başvuran kişilerin tamamına ya da bir kısmına eposta gönderilebilmeli - 1, 2 ve 3 tercihlere göre de seçim yapılabilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#96]
1, 2 ve 3 tercihlere göre de seçim yapılabilmeli. (Buna ayrı bir uygulama yazılacak. Mailman listesine filtreye göre ekleme çıkarma yapılabilecek.)

**Comment by dfisek** [comment]
#89 gerçekleştirildiğinde bu da çözülmüş oluyor.
