### ISSUE TITLE
Katılımcı tercih doldurulana kadar başvurusunu iptal edebilmeli tercih değiştirebilmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#97]
Katılımcı tercih doldurulana kadar başvurusunu iptal edebilmeli tercih değiştirebilmeli. Katılımcı herhangi bir nedenle "iptal" işlemiyaptığında nedenini yazabileceği bir alan olmalı.

**Comment by ozgebarbaros** [comment]
Katılımcı başvuru tarihleri içerisinde istediği gibi tercih değişikliği iptal vs. yapabilir. Tüm başvurularımı iptal et dediğinde "Katılımcı başvurularını iptal etti. İptal sebebi:..." diye journal'ına not düşülür.
