### ISSUE TITLE
Kabul dondurulduktan sonra katılımcı başvurusunu iptal ederse journal'ına not düşülmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#98]
Kabul dondurultutkan sonra katılımcı başvurusunu iptal ederse, "kampa kabul edildikten sonra, kampa x gün kala başvurusunu iptal etti" diye journal'ına not düşülmeli

**Comment by ozgebarbaros** [comment]
TrainessCourseRecord modeline eğitmen tarafından onaylanma tarihi eklenmeli. Kabul aldıktan sonra kursa şu kadar gün kala başvurusunu iptal etti diye not düşülecek.

**Comment by ozgebarbaros** [comment]
başvuru süresi bitiminde kullanıcı hiç bir kursa kabul almadan tüm başvurularını iptal ederse journal'ına "Kursların başlamasına x gun kala tüm başvurularını iptal etti." diye not düşülür. Eğer bir iptal sebebi girmişse not şu şekilde olur: "Kursların başlamasına x gun kala tüm başvurularını iptal etti. İptal sebebi: ...."
başvuru süresi bitiminden sonra kabul almış olmasına rağmen tüm başvurularını iptal ederse ve bir iptal sebebi belirtirse not şu şekilde olur: "Kursların başlamasına x gun kala tüm başvurularını iptal etti. Tercihi kursun başlamasına y gün kala kabul edilmiş. İptal sebebi: ...."
