### ISSUE TITLE
Kabul dondurultutkan sonra katılımcı başvurusunu iptal ederse journal'ına not düşülmeli

### ISSUE THREAD

**Issue by sdemircan** [akademikbilisim/ab-kurs-kayit#99]
Kabul dondurultutkan sonra katılımcı başvurusunu iptal ederse, "kampa kabul edildikten sonra, kampa x gün kala başvurusunu iptal etti" diye journal'ına not düşülmeli

**Comment by ozgebarbaros** [comment]
#98 ile aynı
